import { GraviButton, Horizontal, Texto, Vertical } from '@gravitate-js/excalibrr'
import {
  IndexOfferFormulaComponent,
  IndexPricingFormData,
  SpecialOfferMetadataResponseData,
} from '@modules/Dashboard/SpecialOffers/Api/types.schema'
import { FormulaDiff } from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Components/ConfigureIndexPrice/Components/FormulaDiff'
import { IndexOfferComponentsColumnDefs } from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Components/ConfigureIndexPrice/Components/IndexOfferComponentsColumnDefs'
import { blankFormulaComponentRow } from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Components/ConfigureIndexPrice/Utils/Constants'
import {
  generateIndexOfferDisplayName,
  validateFormulaComponents,
} from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Components/ConfigureIndexPrice/Utils/IndexFormHelpers'
import {
  mapIndexMetadataToSelectorMetadata,
  mapTemplateToComponents,
  mapToFormulaMetadata,
} from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Components/ConfigureIndexPrice/Utils/TemplateHelpers'
import { FormulaTemplateDetails } from '@modules/FormulaTemplates/Api/types.schema'
import { FormulaComponentsGrid } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/FormulaComponentsGrid'
import { PricingDisplaySection } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/PricingDisplaySection'
import { FormulaTemplateSelector } from '@modules/FormulaTemplates/Components/FormulaTemplateSelector/FormulaTemplateSelector'
import { SectionHeader } from '@modules/Dashboard/SpecialOffers/Components/QuickCreate/Components/SectionHeader'
import { initialFilters } from '@modules/FormulaTemplates/Components/FormulaTemplateSelector/Util/Constants'
import { FormulaComponentRow } from '@modules/FormulaTemplates/Util/formConstants'
import { getAutoGeneratedPricingDisplayText } from '@modules/FormulaTemplates/Util/formHelpers'
import type { FormInstance } from 'antd'
import { Drawer, Form, Select } from 'antd'
import { PlusOutlined } from '@ant-design/icons'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'

interface QuickIndexPriceProps {
  metadata?: SpecialOfferMetadataResponseData
  formulaForm: FormInstance
  offerForm: FormInstance
  savedIndexData?: IndexPricingFormData | null
  onSaveIndexPricing: (data: IndexPricingFormData | null) => void
  /** Selected product-location TradeEntrySetupId — scopes the template filter + carries ids into the payload. */
  selectedSetupId?: number
  isActive: boolean
  showIndexError: boolean
  setShowIndexError: (v: boolean) => void
}

/**
 * Quick-create price formula — the inline version of the index-offer table.
 *
 * Per the round-3 wireframe and Frank's review: an empty state offers "Choose a formula template"
 * (opens the EXISTING template chooser, narrowed to the selected product) or "Build from scratch".
 * Either way the same index-offer component grid populates RIGHT HERE, editable, with the
 * differential and a read-only price-formula display — the only relevant pieces. No "basis" field.
 * Effective time / weekend / holiday are surfaced after the differential via progressive disclosure
 * ("View pricing terms" → static summary → Edit dropdowns), prefilled from the preset and editable
 * per deal. Save-as-template stays in Full setup.
 */
export function QuickIndexPrice({
  metadata,
  formulaForm,
  offerForm,
  savedIndexData,
  onSaveIndexPricing,
  selectedSetupId,
  isActive,
  showIndexError,
  setShowIndexError,
}: QuickIndexPriceProps) {
  const idxMeta = metadata?.IndexOfferMetaData
  const idRef = useRef(0)
  const hydratedRef = useRef(false)

  const [formulaComponents, setFormulaComponents] = useState<IndexOfferFormulaComponent[]>([])
  const [isChoosingTemplate, setIsChoosingTemplate] = useState(false)
  const [showCustomDisplayName, setShowCustomDisplayName] = useState(false)

  // Pricing context (effective time / weekend / holiday) — glanceable, edited per deal via a
  // 3-stage disclosure (View → static → Edit). Values live only in the committed indexPricingData,
  // so these hold explicit per-deal overrides; undefined falls back to the preset/template default.
  const [showContext, setShowContext] = useState(false)
  const [editContext, setEditContext] = useState(false)
  const [effectiveTime, setEffectiveTime] = useState<string>()
  const [weekendRule, setWeekendRule] = useState<string>()
  const [holidayRule, setHolidayRule] = useState<string>()
  const effEffective =
    effectiveTime ?? savedIndexData?.PricingEffectiveTimes ?? idxMeta?.EffectiveTimes?.[0]?.Value ?? 'AllDay'
  const effWeekend = weekendRule ?? savedIndexData?.PricingWeekendBehavior ?? idxMeta?.WeekendRuleOptions?.[0] ?? 'Friday'
  const effHoliday =
    holidayRule ?? savedIndexData?.PricingHolidayBehavior ?? idxMeta?.HolidayRuleOptions?.[0] ?? 'PriorBusinessDay'
  const effectiveLabel = idxMeta?.EffectiveTimes?.find((o) => o.Value === effEffective)?.Text ?? effEffective
  // camelCase/PascalCase tokens (e.g. 'PriorBusinessDay') → "Prior business day" for display only.
  const humanize = (s: string) => {
    const spaced = s.replace(/([a-z])([A-Z])/g, '$1 $2')
    return spaced.charAt(0).toUpperCase() + spaced.slice(1).toLowerCase()
  }

  const setup = useMemo(
    () => metadata?.ProductLocationSelections?.find((s) => s.TradeEntrySetupId === selectedSetupId),
    [metadata?.ProductLocationSelections, selectedSetupId]
  )

  const selectorMetadata = useMemo(() => mapIndexMetadataToSelectorMetadata(idxMeta), [idxMeta])
  const formulaMetadata = useMemo(() => mapToFormulaMetadata(idxMeta), [idxMeta])

  const autoText = useMemo(
    () => (formulaComponents.length ? getAutoGeneratedPricingDisplayText(formulaComponents, formulaMetadata) : ''),
    [formulaComponents, formulaMetadata]
  )

  const differential = Form.useWatch('FormulaDifferential', formulaForm)

  // Grid plumbing — same column defs + grid metadata the index-offer builder uses.
  const handleDelete = useCallback(
    (data: IndexOfferFormulaComponent) => {
      const next = formulaComponents.filter((row) => row.IdForGrid !== data.IdForGrid)
      setFormulaComponents(next)
      formulaForm.setFieldsValue({ FormulaTemplateVariables: next })
    },
    [formulaComponents, formulaForm]
  )
  const columnDefs = useMemo(
    () => IndexOfferComponentsColumnDefs({ metadata: idxMeta, handleDelete }),
    [idxMeta, handleDelete]
  )
  const gridMetadata = useMemo(() => {
    if (!idxMeta) return undefined
    const allPriceTypes = Object.values(idxMeta.PublisherPriceTypes || {}).flat()
    return {
      Publishers: idxMeta.PricePublishers,
      Instruments: idxMeta.PriceInstruments,
      DateRules: idxMeta.TradePriceValuationRules,
      PriceTypes: allPriceTypes,
      PublisherPriceTypes: idxMeta.PublisherPriceTypes,
    }
  }, [idxMeta])

  // Narrow the template list to the selected product — but only when a template actually matches,
  // so the chooser never opens to an empty list.
  const seedFilters = useMemo(() => {
    const productIdStr = setup?.ProductId?.toString()
    if (!productIdStr) return initialFilters
    const anyMatch = (selectorMetadata?.FormulaTemplates ?? []).some((t) =>
      t.FormulaTemplateApplicableProducts?.some((p) => p.ProductId?.toString() === productIdStr)
    )
    return anyMatch ? { ...initialFilters, ProductIds: [productIdStr] } : initialFilters
  }, [setup, selectorMetadata])

  // Hydrate the grid once when a preset (or any externally-saved formula) arrives.
  useEffect(() => {
    if (hydratedRef.current) return
    const comps = savedIndexData?.formulaComponents
    if (comps && comps.length && formulaComponents.length === 0) {
      setFormulaComponents(comps)
      formulaForm.setFieldsValue({
        FormulaTemplateVariables: comps,
        FormulaDifferential: savedIndexData?.FormulaDifferential ?? 0,
        PricingDisplayText: savedIndexData?.PricingDisplayText,
        ProductId: setup?.ProductId?.toString(),
        LocationId: setup?.LocationId?.toString(),
      })
      hydratedRef.current = true
    }
  }, [savedIndexData, setup, formulaComponents.length, formulaForm])

  // External clear (reset / "new offer" / explicit remove) → return to empty state.
  useEffect(() => {
    if (savedIndexData === null) {
      hydratedRef.current = false
      setShowCustomDisplayName(false)
      setShowContext(false)
      setEditContext(false)
      setEffectiveTime(undefined)
      setWeekendRule(undefined)
      setHolidayRule(undefined)
      if (formulaComponents.length) setFormulaComponents([])
    }
  }, [savedIndexData]) // eslint-disable-line react-hooks/exhaustive-deps

  // Auto-commit a complete IndexPricingFormData whenever the grid / differential / display changes,
  // so Step-1's required `IndexPrice` field stays satisfied without a separate Save step.
  // NOTE: savedIndexData is intentionally NOT a dep — this effect writes it back, and re-reading it
  // would loop. The effective-time / weekend / holiday fallbacks are read from metadata.
  useEffect(() => {
    if (!formulaComponents.length) return
    const customText = formulaForm.getFieldValue('PricingDisplayText')
    const indexData: IndexPricingFormData = {
      ProductId: setup?.ProductId as number,
      LocationId: setup?.LocationId as number,
      PricingEffectiveTimes: effEffective,
      PricingWeekendBehavior: effWeekend,
      PricingHolidayBehavior: effHoliday,
      FormulaDifferential: differential ?? 0,
      formulaComponents: formulaComponents.map((c) =>
        c.DisplayName ? c : { ...c, DisplayName: generateIndexOfferDisplayName(c, idxMeta) }
      ),
      PricingDisplayText: showCustomDisplayName && customText ? customText : autoText,
    }
    onSaveIndexPricing(indexData)
    offerForm.setFieldsValue({ IndexPrice: indexData })
    setShowIndexError(false)
  }, [formulaComponents, differential, showCustomDisplayName, autoText, effectiveTime, weekendRule, holidayRule]) // eslint-disable-line react-hooks/exhaustive-deps

  const addRow = () => {
    const next = [...formulaComponents, blankFormulaComponentRow(idRef.current++)]
    setFormulaComponents(next)
    formulaForm.setFieldsValue({ FormulaTemplateVariables: next })
  }

  const onTemplateSelect = (template: FormulaTemplateDetails) => {
    const next = [...formulaComponents, ...mapTemplateToComponents(template, idRef, idxMeta)]
    setFormulaComponents(next)
    formulaForm.setFieldsValue({ FormulaTemplateVariables: next })
    if (!showCustomDisplayName && template.PricingDisplayText) {
      const auto = getAutoGeneratedPricingDisplayText(next, formulaMetadata)
      if (template.PricingDisplayText !== auto) {
        setShowCustomDisplayName(true)
        formulaForm.setFieldsValue({ PricingDisplayText: template.PricingDisplayText })
      }
    }
    setIsChoosingTemplate(false)
  }

  const removeFormula = () => {
    setFormulaComponents([])
    setShowCustomDisplayName(false)
    formulaForm.setFieldsValue({ FormulaTemplateVariables: [], FormulaDifferential: undefined, PricingDisplayText: undefined })
    onSaveIndexPricing(null)
    offerForm.setFieldsValue({ IndexPrice: undefined })
    hydratedRef.current = false
  }

  const hasFormula = formulaComponents.length > 0
  // Right-size the embedded grid to its rows (measured: header 49 + row 50, no persistent
  // h-scrollbar) so a single-row formula doesn't leave a tall empty well. Clamped so long
  // formulas still scroll instead of growing without bound.
  const gridHeight = Math.min(53 + formulaComponents.length * 50, 420)

  // A preset populates the whole form in one busy frame, so the grid can mount before its
  // container has a settled width — AG Grid then lays out zero columns and never recovers
  // (it watches the container via ResizeObserver, so a window resize doesn't fix it). Remount
  // it once on the next frame, by which point the width is final, and columns lay out correctly.
  const [gridRemountKey, setGridRemountKey] = useState(0)
  useEffect(() => {
    if (!hasFormula) return
    const raf = requestAnimationFrame(() => setGridRemountKey((k) => k + 1))
    return () => cancelAnimationFrame(raf)
  }, [hasFormula])

  return (
    <Vertical className={'qc-section p-4'} style={{ display: isActive ? 'flex' : 'none', gap: 16 }}>
      <SectionHeader title={'Price formula'} />

      {!hasFormula ? (
        <Vertical
          verticalCenter
          horizontalCenter
          className={'qc-formula-empty p-4 border-radius-10'}
          style={{ gap: 8, ...(showIndexError ? { borderColor: 'var(--theme-error)' } : {}) }}
        >
          <Texto className={'qc-formula-sigma'}>Σ</Texto>
          <Texto category={'h5'}>No price formula yet</Texto>
          <Texto className={'text-14'} appearance={'medium'} style={{ textAlign: 'center', maxWidth: 460 }}>
            Pick a saved formula template (recommended), or build from scratch. Picking a product first filters the
            list.
          </Texto>
          <Horizontal verticalCenter className={'mt-2'} style={{ gap: 8 }}>
            <GraviButton theme1 buttonText={'Choose a formula template'} onClick={() => setIsChoosingTemplate(true)} />
            <GraviButton appearance={'outline'} buttonText={'Build from scratch'} onClick={addRow} />
          </Horizontal>
        </Vertical>
      ) : (
        <Form form={formulaForm} layout={'vertical'} component={false}>
          <Vertical className={'qc-formula-built bordered border-radius-10 p-4'} style={{ gap: 16 }}>
            <Horizontal justifyContent={'space-between'} verticalCenter style={{ flexWrap: 'wrap', gap: 8 }}>
              <Texto weight={'bold'} className={'text-14'}>
                Components
              </Texto>
              <Horizontal verticalCenter style={{ gap: 8 }}>
                <GraviButton appearance={'outline'} buttonText={'Add row'} icon={<PlusOutlined />} onClick={addRow} />
                <GraviButton
                  appearance={'outline'}
                  buttonText={'Add a template'}
                  icon={<PlusOutlined />}
                  onClick={() => setIsChoosingTemplate(true)}
                />
              </Horizontal>
            </Horizontal>

            <div style={{ width: '100%', height: gridHeight }}>
              <FormulaComponentsGrid
                key={gridRemountKey}
                columnDefs={columnDefs}
                setFormulaComponents={
                  setFormulaComponents as React.Dispatch<React.SetStateAction<FormulaComponentRow[]>>
                }
                formulaComponents={formulaComponents as FormulaComponentRow[]}
                form={formulaForm}
                metadata={gridMetadata}
                rowGroupPanelShow={'never'}
                sideBar={false}
              />
            </div>

            {/* Backstop validator — kept hidden so it doesn't reserve a ~49px control row
                (and a phantom flex gap) between the grid and the differential. Hidden Form.Items
                still validate; the grid cells surface per-row errors. */}
            <Form.Item
              name={'FormulaTemplateVariables'}
              rules={[{ validator: validateFormulaComponents(idxMeta) }]}
              hidden
            >
              <div />
            </Form.Item>

            <div className={'qc-diff'}>
              <FormulaDiff isAuction={false} />
            </div>

            {/* Pricing context — glanceable, edited per deal. 3-stage disclosure: View → static → Edit.
                Extra top/bottom margin sets this band apart from the differential above and the
                display section below (stacks on the card's 16px flex gap → ~24px flanking). */}
            <Vertical style={{ gap: 8, marginTop: 8, marginBottom: 8 }}>
              {!showContext ? (
                <Horizontal>
                  <GraviButton
                    className={'ghost-gravi-button qc-link-btn p-0'}
                    buttonText={'View pricing terms'}
                    onClick={() => setShowContext(true)}
                  />
                </Horizontal>
              ) : (
                <Vertical style={{ gap: 8 }}>
                  <Horizontal verticalCenter justifyContent={'space-between'} style={{ flexWrap: 'wrap', gap: 8 }}>
                    <Texto weight={'bold'} className={'text-14'}>
                      Pricing terms
                    </Texto>
                    <GraviButton
                      className={'ghost-gravi-button qc-link-btn p-0'}
                      buttonText={editContext ? 'Done' : 'Edit'}
                      onClick={() => setEditContext((e) => !e)}
                    />
                  </Horizontal>
                  {!editContext ? (
                    <Vertical style={{ gap: 4 }}>
                      {[
                        { label: 'Effective Time', value: effectiveLabel },
                        { label: 'Weekend Rule', value: humanize(effWeekend) },
                        { label: 'Holiday Rule', value: humanize(effHoliday) },
                      ].map((r) => (
                        <Horizontal key={r.label} style={{ gap: 6 }}>
                          <Texto className={'text-14 text-medium'}>{r.label}:</Texto>
                          <Texto className={'text-14'}>{r.value}</Texto>
                        </Horizontal>
                      ))}
                    </Vertical>
                  ) : (
                    <Horizontal style={{ gap: 16, flexWrap: 'wrap' }}>
                      <Vertical style={{ flex: 1, gap: 4, minWidth: 180 }}>
                        <Texto category={'label'} weight={'bold'}>
                          Effective Time
                        </Texto>
                        <Select
                          style={{ width: '100%' }}
                          value={effEffective}
                          onChange={(v) => setEffectiveTime(v)}
                          options={(idxMeta?.EffectiveTimes ?? []).map((o) => ({ value: o.Value, label: o.Text }))}
                          popupClassName={'qc-pop'}
                        />
                      </Vertical>
                      <Vertical style={{ flex: 1, gap: 4, minWidth: 180 }}>
                        <Texto category={'label'} weight={'bold'}>
                          Weekend Rule
                        </Texto>
                        <Select
                          style={{ width: '100%' }}
                          value={effWeekend}
                          onChange={(v) => setWeekendRule(v)}
                          options={(idxMeta?.WeekendRuleOptions ?? []).map((v) => ({ value: v, label: humanize(v) }))}
                          popupClassName={'qc-pop'}
                        />
                      </Vertical>
                      <Vertical style={{ flex: 1, gap: 4, minWidth: 180 }}>
                        <Texto category={'label'} weight={'bold'}>
                          Holiday Rule
                        </Texto>
                        <Select
                          style={{ width: '100%' }}
                          value={effHoliday}
                          onChange={(v) => setHolidayRule(v)}
                          options={(idxMeta?.HolidayRuleOptions ?? []).map((v) => ({ value: v, label: humanize(v) }))}
                          popupClassName={'qc-pop'}
                        />
                      </Vertical>
                    </Horizontal>
                  )}
                </Vertical>
              )}
            </Vertical>

            {/* Title rendered here (matching the "Components" header) instead of the shared
                SectionTitle, so it reads at the same size/weight; section's own title suppressed. */}
            <Texto weight={'bold'} className={'text-14'}>
              Price formula (display)
            </Texto>
            <PricingDisplaySection
              pricingDisplayText={autoText}
              showCustomInput={showCustomDisplayName}
              setShowCustomInput={setShowCustomDisplayName}
              form={formulaForm}
              title={''}
            />

            <Horizontal>
              <GraviButton className={'ghost-gravi-button qc-link-btn p-0'} buttonText={'Remove formula'} onClick={removeFormula} />
            </Horizontal>
          </Vertical>
        </Form>
      )}

      <Drawer
        className={'qc-template-drawer'}
        open={isChoosingTemplate}
        onClose={() => setIsChoosingTemplate(false)}
        placement={'bottom'}
        height={'85vh'}
        title={'Choose a formula template'}
        styles={{ body: { backgroundColor: 'var(--bg-2)', paddingTop: 0 } }}
        destroyOnHidden
      >
        {selectorMetadata && (
          <FormulaTemplateSelector
            isChoosingTemplate={isChoosingTemplate}
            setIsChoosingTemplate={setIsChoosingTemplate}
            metadata={selectorMetadata}
            onTemplateSelect={onTemplateSelect}
            manageTemplatesLink={'/Admin/FormulaTemplates'}
            initialFilters={seedFilters}
          />
        )}
      </Drawer>
    </Vertical>
  )
}
