import { dateFormat } from '@components/TheArmory/helpers'
import {
  CreateSpecialOfferRequest,
  IndexOfferMetaData,
  IndexPricingFormData,
  IndexPricingInfo,
} from '@modules/Dashboard/SpecialOffers/Api/types.schema'
import { convertComponentsToFormula } from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Util/indexConfigHelpers'
import { step1Fields, step2Fields } from '@modules/Dashboard/SpecialOffers/utils/Constants/FormConstants'
import { getFormulaAutoGeneratedDisplayText } from '@modules/FormulaTemplates/Util/formHelpers'
import { FormInstance } from 'antd/lib/form/Form'
import moment from 'moment'
export interface createPayloadFromValuesProps {
  values: any
  indexPricingData?: IndexPricingFormData
  formulaMetadata?: IndexOfferMetaData
}
export function createPayloadFromValues({
  values,
  indexPricingData,
  formulaMetadata,
}: createPayloadFromValuesProps): CreateSpecialOfferRequest {
  const tradeEntrySetupIds =
    typeof values.ProductLocation === 'number' ? [values.ProductLocation] : values.ProductLocation
  const InvitationTriggerDateTimeTZ = values.SendInvitesOnCreate
    ? constructDateTime(moment(), moment().add(1, 'minutes'))
    : constructDateTime(values.InviteTriggerDate, values.InviteTriggerTime)

  let indexPricingInfo: IndexPricingInfo | undefined
  if (indexPricingData) {
    const formula = convertComponentsToFormula(indexPricingData)
    indexPricingInfo = {
      ProductId: indexPricingData.ProductId,
      LocationId: indexPricingData.LocationId,
      EffectiveTime: indexPricingData.PricingEffectiveTimes,
      WeekendRule: indexPricingData.PricingWeekendBehavior,
      HolidayRule: indexPricingData.PricingHolidayBehavior,
      AdditionalFreetextTerms: indexPricingData.AdditionalFreetextTerms,
      PricingFormulaDefaultText: getFormulaAutoGeneratedDisplayText(
        indexPricingData.formulaComponents,
        formulaMetadata
      ),
      ContractDifferential: indexPricingData.FormulaDifferential ?? 0,
      Formula: formula,
      StartDate: constructDateTimeString(values.VisibilityWindowStartDate, values.VisibilityWindowStartTime),
      EndDate: constructDateTimeString(values.VisibilityWindowEndDate, values.VisibilityWindowEndTime),
      InternalFormulaDisplayNameOverride: indexPricingData.InternalDisplayName || undefined,
      ExternalFormulaDisplayNameOverride: indexPricingData.ExternalDisplayName || undefined,
    }
  }

  return {
    SpecialOfferTemplateId: values.SpecialOfferTemplateId,
    MinimumVolumePerOrder: values.MinimumVolumePerOrder,
    MaximumVolumePerOrder: values.MaximumVolumePerOrder,
    VolumeIncrement: values.VolumeIncrement,
    TotalVolume: values.TotalVolume,
    ReservePrice: indexPricingData?.ReservePrice ?? values.ReservePrice ?? undefined,
    FixedPrice: values.ReservePrice || undefined,
    VisibilityStartDateTime: constructDateTimeString(
      values.VisibilityWindowStartDate,
      values.VisibilityWindowStartTime
    ),
    VisibilityEndDateTime: constructDateTimeString(values.VisibilityWindowEndDate, values.VisibilityWindowEndTime),
    OrderEffectiveStartDateTime: constructDateTimeString(values.PickupWindowStartDate, values.PickupWindowStartTime),
    OrderEffectiveEndDateTime: constructDateTimeString(values.PickupWindowEndDate, values.PickupWindowEndTime),
    CounterPartyIds: values.CounterPartyIds,
    TradeEntrySetupIds: tradeEntrySetupIds,
    InvitationTriggerDateTimeTZ,
    IndexPricingInfo: indexPricingInfo,
  }
}

export function constructDateTimeString(date: moment.Moment, time?: moment.Moment): string {
  return moment(date)
    .set({
      hour: time ? time.get('hour') : 0,
      minute: time ? time.get('minute') : 0,
      second: 0,
    })
    .format(dateFormat.ISO)
}
export function constructDateTime(date: moment.Moment, time?: moment.Moment): Date {
  return moment(date)
    .set({
      hour: time ? time.get('hour') : 0,
      minute: time ? time.get('minute') : 0,
      second: 0,
    })
    .toDate()
}
export function validateFormFields({
  form,
  goNext,
  currentStep,
  setShowIndexError,
  isIndexPricing,
}: {
  form: FormInstance
  goNext: () => void
  currentStep: number
  setShowIndexError: React.Dispatch<React.SetStateAction<boolean>>
  isIndexPricing: boolean
}) {
  const fieldsToValidate = isIndexPricing ? step1Fields.concat('IndexPrice') : step1Fields
  if (currentStep === 1) {
    form
      .validateFields(['ProductLocation'])
      .then(() => {
        form
          .validateFields(fieldsToValidate)
          .then((e) => {
            setShowIndexError(false)
            goNext()
          })
          .catch(({ values, errorFields }) => {
            if (errorFields?.length && isIndexPricing) {
              setShowIndexError(errorFields?.find((f) => f.name[0] === 'IndexPrice')?.errors?.length > 0)
            }
          })
      })
      .catch(() => {})
  }
  if (currentStep === 2) {
    form.validateFields(step2Fields).then(() => goNext())
  }
}
