/**
 * One-off + re-runnable backfill: bundle the wireframe-index skill into every
 * existing project and regenerate their (template-generated) CLAUDE.md files so
 * they pick up the strengthened wireframe-index wording + the portable,
 * project-relative backup path. Idempotent. Run: npx tsx scripts/backfill-wireframe-skill.ts
 */
import fs from "node:fs/promises";
import path from "node:path";
import { renderClaudeMd, renderRoundClaudeMd } from "../server/claudemd.js";
import {
  PROJECTS_PATH,
  projectClaudeMd,
  projectLofiDir,
  projectMetaFile,
  projectWireframeIndexSkillDir,
  WIREFRAME_INDEX_SKILL_PATH,
} from "../server/paths.js";

const GEN_MARKER = "Generated by Project Hub";

async function exists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

function dateFrom(text: string, fallback: string): string {
  const m = text.match(/Generated by Project Hub on (\S+?)\.?\s*$/m);
  return m ? m[1].replace(/\.$/, "") : fallback;
}

async function main(): Promise<void> {
  const entries = await fs.readdir(PROJECTS_PATH, { withFileTypes: true });
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    const slug = e.name;
    if (!(await exists(projectMetaFile(slug)))) continue;
    const meta = JSON.parse(await fs.readFile(projectMetaFile(slug), "utf8"));
    const name: string = meta.name ?? slug;
    const port: number = meta.port ?? 0;
    const createdAt: string = meta.createdAt ?? new Date().toISOString();

    // 1. Bundle the skill (overwrites so it stays in sync with the vendored source)
    await fs.cp(WIREFRAME_INDEX_SKILL_PATH, projectWireframeIndexSkillDir(slug), {
      recursive: true,
      force: true,
    });
    console.log(`[${slug}] bundled wireframe-index skill`);

    // 2. Project CLAUDE.md (guarded to template-generated files)
    const pc = projectClaudeMd(slug);
    if (await exists(pc)) {
      const cur = await fs.readFile(pc, "utf8");
      if (cur.includes(GEN_MARKER)) {
        await fs.writeFile(
          pc,
          renderClaudeMd({ name, slug, port, isoDate: dateFrom(cur, createdAt) }),
          "utf8",
        );
        console.log(`[${slug}] regenerated project CLAUDE.md`);
      } else {
        console.log(`[${slug}] project CLAUDE.md not template-generated — skipped`);
      }
    }

    // 3. Round CLAUDE.md files
    const lofi = projectLofiDir(slug);
    if (!(await exists(lofi))) continue;
    const rounds = (await fs.readdir(lofi, { withFileTypes: true }))
      .filter((d) => d.isDirectory() && /^round-\d+$/.test(d.name))
      .map((d) => ({ dir: d.name, n: Number(d.name.slice("round-".length)) }));
    for (const r of rounds) {
      const rc = path.join(lofi, r.dir, "CLAUDE.md");
      if (!(await exists(rc))) continue;
      const cur = await fs.readFile(rc, "utf8");
      if (!cur.includes(GEN_MARKER)) {
        console.log(`[${slug}] ${r.dir}/CLAUDE.md not template-generated — skipped`);
        continue;
      }
      const parent = rounds
        .filter((o) => o.n < r.n)
        .reduce((mx, o) => Math.max(mx, o.n), 0);
      await fs.writeFile(
        rc,
        renderRoundClaudeMd({
          projectName: name,
          slug,
          roundN: r.n,
          parentRoundN: parent,
          isoDate: dateFrom(cur, createdAt),
        }),
        "utf8",
      );
      console.log(`[${slug}] regenerated ${r.dir}/CLAUDE.md (parent ${parent})`);
    }
  }
  console.log("backfill complete");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
