import { Vertical } from '@gravitate-js/excalibrr'
import { AutoGeneratedFormula } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/AutoGeneratedFormula'
import { CustomFormulaName } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/CustomFormulaName'
import { SectionTitle } from '@modules/FormulaTemplates/Util/formHelpers'
import { Checkbox } from 'antd'
import { FormInstance } from 'antd/lib/form/Form'

interface FormulaDisplayNameProps {
  formula: string
  form: FormInstance
  showCustomInputForSeller: boolean
  setShowCustomInputForSeller: React.Dispatch<React.SetStateAction<boolean>>
  showCustomInputForBuyer: boolean
  setShowCustomInputForBuyer: React.Dispatch<React.SetStateAction<boolean>>
}

export function FormulaDisplayName({
  formula,
  form,
  showCustomInputForSeller,
  setShowCustomInputForSeller,
  showCustomInputForBuyer,
  setShowCustomInputForBuyer,
}: FormulaDisplayNameProps) {
  return (
    <Vertical>
      <SectionTitle title={'Formula Display Name'} />
      <Vertical className={'gap-10'}>
        <AutoGeneratedFormula formula={formula} />
      </Vertical>
      <Vertical className={'gap-10 my-2'}>
        <Checkbox
          onChange={(value) => {
            setShowCustomInputForSeller(value.target.checked)
            if (!value.target.checked) form.resetFields(['InternalDisplayName'])
          }}
          checked={showCustomInputForSeller}
        >
          Override Internal Display Name (Seller View)
        </Checkbox>

        {showCustomInputForSeller && (
          <CustomFormulaName
            title={'Internal Display Name (Seller View)'}
            placeholder={'Enter custom formula display name for internal/seller view'}
            formItemName={'InternalDisplayName'}
          />
        )}
      </Vertical>
      <Vertical className={'gap-10'}>
        <Checkbox
          className={'m-0'}
          onChange={(value) => {
            setShowCustomInputForBuyer(value.target.checked)
            if (!value.target.checked) form.resetFields(['ExternalDisplayName'])
          }}
          checked={showCustomInputForBuyer}
        >
          Override External Display Name (Buyer View)
        </Checkbox>

        {showCustomInputForBuyer && (
          <CustomFormulaName
            title={'External Display Name (Buyer View)'}
            placeholder={'Enter custom display formula name for external/buyer view'}
            formItemName={'ExternalDisplayName'}
          />
        )}
      </Vertical>
    </Vertical>
  )
}
