import { CopyOutlined } from '@ant-design/icons'
import { Texto } from '@gravitate-js/excalibrr'
import { Button, Input, message } from 'antd'
import { copyToClipboard } from '@utils/clipboard'

interface AutoGeneratedPricingDisplayProps {
  pricingDisplayText: string
}

export function AutoGeneratedPricingDisplay({ pricingDisplayText }: AutoGeneratedPricingDisplayProps) {
  const handleCopy = async () => {
    const ok = await copyToClipboard(pricingDisplayText)
    if (ok) message.success('Copied to clipboard')
    else message.error('Failed to copy')
  }

  return (
    <>
      <Texto>Auto-Generated</Texto>
      <div style={{ position: 'relative' }}>
        <Input.TextArea
          id='autoGeneratedPricingDisplayInput'
          disabled
          value={pricingDisplayText}
          className={'border-radius-4'}
          style={{
            fontSize: '13px',
            fontFamily: 'monospace',
            borderRadius: '3px',
            color: 'var(--gray-600)',
            resize: 'none',
            pointerEvents: 'none',
          }}
          autoSize={{ minRows: 1 }}
          showCount
          maxLength={1000}
        />
        <Button
          icon={<CopyOutlined />}
          onClick={handleCopy}
          type='text'
          size='small'
          title='Copy to clipboard'
          style={{
            position: 'absolute',
            top: '2px',
            right: '6px',
            zIndex: 1,
            pointerEvents: 'auto',
          }}
          aria-label='Copy to clipboard'
        />
      </div>
    </>
  )
}
