import { Texto, Vertical } from '@gravitate-js/excalibrr'
import { AutoGeneratedPricingDisplay } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/AutoGeneratedPricingDisplay'
import { CustomFormulaName } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/CustomFormulaName'
import { SectionTitle } from '@modules/FormulaTemplates/Util/formHelpers'
import { Checkbox } from 'antd'
import { useState } from 'react'
import type { FormInstance } from 'antd'

interface PricingDisplaySectionProps {
  pricingDisplayText: string
  showCustomInput: boolean
  setShowCustomInput: (value: boolean) => void
  form: FormInstance
  title?: string
  checkboxLabel?: string
}

export function PricingDisplaySection({
  pricingDisplayText,
  showCustomInput,
  setShowCustomInput,
  form,
  title = 'Pricing Display Name',
  checkboxLabel = 'Custom Pricing Display Name',
}: PricingDisplaySectionProps) {
  const [showCustomNameLengthError, setShowCustomNameLengthError] = useState(false)
  const handleCheckboxChange = (checked: boolean) => {
    setShowCustomInput(checked)
    if (checked) {
      form.setFieldsValue({ PricingDisplayText: pricingDisplayText })
    } else {
      form.setFieldsValue({ PricingDisplayText: null })
    }
  }

  return (
    <>
      {title ? <SectionTitle title={title} /> : null}
      <Vertical className='mb-3' style={{ width: '100%', gap: 10 }}>
        <Vertical>
          <AutoGeneratedPricingDisplay pricingDisplayText={pricingDisplayText} />
          {pricingDisplayText?.length > 1000 && !showCustomInput && (
            <Texto className={'ml-4'} appearance={'error'}>
              Pricing Display Name cannot be more than 1,000 characters long. Please enter a custom name or adjust the
              components.
            </Texto>
          )}
        </Vertical>
        <Checkbox onChange={(value) => handleCheckboxChange(value.target.checked)} checked={showCustomInput}>
          {checkboxLabel}
        </Checkbox>

        {showCustomInput && (
          <Vertical>
            <CustomFormulaName
              setShowCustomNameLengthError={setShowCustomNameLengthError}
              title={''}
              placeholder={'Enter pricing display name or copy from auto-generated above'}
              formItemName={'PricingDisplayText'}
              onBlur={() => {
                const value = form.getFieldValue('PricingDisplayText')
                if (!value || !value.trim()) {
                  form.setFieldsValue({ PricingDisplayText: pricingDisplayText })
                }
              }}
            />
            {showCustomNameLengthError && (
              <Texto className={'ml-2'} appearance={'error'}>
                Pricing Display Name cannot be more than 1,000 characters long.
              </Texto>
            )}
          </Vertical>
        )}
      </Vertical>
    </>
  )
}
