export const newLoadingNumberCreateConfig = (selectOptions) => {
  return [
    {
      step_title: 'AddNewLoadingNumber',
      form_title: 'New Loading Number',
      section: [
        {
          name: 'LoadNumber',
          fieldLabel: 'Loading Number *',
          type: 'text',
          input: 'input',
          placeholder: 'Enter Loading Number',
          rules: [
            {
              required: true,
              message: 'Loading Number is required',
            },
          ],
        },
        {
          name: 'Display',
          fieldLabel: 'Display *',
          input: 'input',
          max: 1000,
          min: 0,
          precision: 0,
          placeholder: 'Enter Display',
          rules: [
            {
              required: true,
              message: 'Description required',
            },
          ],
        },
        {
          name: 'CustomerCounterParty',
          fieldLabel: 'Customer',
          input: 'select',
          type: 'text',
          placeholder: 'Select Customer (optional - leave blank for general loading number)',
          options: selectOptions?.CounterParties.map((item) => item.Text),
          allowClear: true,
        },
        {
          name: 'IsActive',
          fieldLabel: 'Is active? *',
          input: 'select',
          placeholder: 'Select status',
          options: ['Active', 'Inactive'],
          rules: [
            {
              required: true,
              message: 'Is active is required',
            },
          ],
        },
        {
          name: 'SupplierCounterParty',
          fieldLabel: 'Supplier',
          input: 'select',
          type: 'text',
          placeholder: 'Select Supplier',
          options: selectOptions?.CounterParties.map((item) => item.Text),
          allowClear: true,
        },
        {
          name: 'CarrierCounterParty',
          fieldLabel: 'Carrier',
          input: 'select',
          type: 'text',
          placeholder: 'Select Carrier',
          options: selectOptions?.CounterParties.map((item) => item.Text),
          allowClear: true,
        },
        {
          name: 'Product',
          fieldLabel: 'Product',
          input: 'select',
          type: 'text',
          placeholder: 'Select Product',
          options: selectOptions?.Products.map((item) => item.Text),
          allowClear: true,
        },
        {
          name: 'OriginLocation',
          fieldLabel: 'Origin',
          input: 'select',
          type: 'text',
          placeholder: 'Select Origin',
          options: selectOptions?.Locations.map((item) => item.Text),
          allowClear: true,
        },
        {
          name: 'DestinationLocation',
          fieldLabel: 'Destination',
          input: 'select',
          type: 'text',
          placeholder: 'Select Destination',
          options: selectOptions?.Locations.map((item) => item.Text),
          allowClear: true,
        },
        {
          name: 'TaxLocation',
          fieldLabel: 'Tax Destination',
          input: 'select',
          type: 'text',
          placeholder: 'Select Tax Destination',
          options: selectOptions?.Locations.map((item) => item.Text),
          allowClear: true,
        },
        {
          name: 'TradeType',
          fieldLabel: 'Trade Type',
          input: 'select',
          type: 'text',
          placeholder: 'Select Trade Type',
          options: selectOptions?.TradeTypes.map((item) => item.Text),
          allowClear: true,
        },
        {
          name: 'Notes',
          fieldLabel: 'Notes',
          input: 'input',
          type: 'text',
          placeholder: 'Enter notes',
          allowClear: true,
        },
      ],
    },
  ]
}
