import {
  EXCALIBRR_DESIGN_PATTERNS_PATH,
  EXCALIBRR_DESIGN_SYSTEM_PATH,
  WIREFRAME_DESIGN_SYSTEM_PATH,
} from "./paths.js";

export interface ClaudeMdInput {
  name: string;
  slug: string;
  port: number;
  isoDate: string;
}

export function renderClaudeMd(input: ClaudeMdInput): string {
  const { name, slug, port, isoDate } = input;
  return `# ${name}

Generated by Project Hub on ${isoDate}.
Branch: \`project/${slug}\` (worktree of ~/freddy/proto-base)
Dev server URL when running: http://localhost:${port}

## What this folder is

A working copy of the Freddy prototype, scoped to one design exploration. All prototype edits happen in \`./prototype/\`, which is a git worktree on its own branch.

## Paths

- \`./prototype/\`            — git worktree of proto-base on \`project/${slug}\` — edit here
- \`./design-system/lofi/\`   — lo-fi wireframe rounds (round-1, round-2, …)
- \`./resources/\`            — briefs, screenshots, reference docs (read-only inputs)
- \`./excalibrr-freddy\`      — symlink to ~/freddy/excalibrr-freddy (do not edit)
- \`./.freddy-project.json\`  — Hub metadata (do not hand-edit)

## Lo-fi wireframes — design system + documentation

Lo-fi wireframe rounds live under \`./design-system/lofi/round-N/\`, seeded by \`./design-system/lofi/KICKOFF.md\`.

- **Build wireframes FROM** the shared wireframe design system at \`${WIREFRAME_DESIGN_SYSTEM_PATH}\` — copy its \`wf-\` component markup verbatim and reference \`--wf-\` tokens by name; start at its \`CLAUDE.md\` → \`DESIGN.md\` → \`reference-guide.html\`.
- **Make each round's index / guide page WITH the \`/wireframe-index\` skill — this is how you make the index page; never hand-write it.** After building a round's wireframes, invoke the skill to generate that round's \`WIREFRAME-GUIDE.html\` (screen catalog, design decisions, changes from previous round, open questions):
  \`\`\`
  /wireframe-index
  \`\`\`
  **Primary:** use the installed \`/wireframe-index\` skill if this session has it (it does in Cowork / claude.ai desktop). **Backup:** if the skill isn't installed, the full skill is bundled with this project at \`./design-system/lofi/wireframe-index-skill/SKILL.md\` — read it and follow it verbatim. Either way the deliverable is an HTML \`WIREFRAME-GUIDE.html\` (never markdown), so the Hub can surface it.
- Each round folder has its own \`CLAUDE.md\` with the per-round working agreement — open it before iterating on that round.

## Hi-fi prototype — design system + patterns

The prototype is built on Excalibrr (\`@gravitate-js/excalibrr\`). Two vendored references in the Hub repo are the source of truth for how to use it — the hi-fi siblings of the wireframe design system above:

- \`${EXCALIBRR_DESIGN_SYSTEM_PATH}/\` — the component reference: every component, its captured states, props, correct usage code, and gotchas. Start at its \`CLAUDE.md\`.
- \`${EXCALIBRR_DESIGN_PATTERNS_PATH}/\` — the layout rulebook: spacing, hierarchy, forms, modals, drawers, page layouts, stated as rules. Start at its \`CLAUDE.md\`.

Consult the patterns BEFORE inventing a layout, and copy component usage from the system reference rather than guessing props. Some production screens violate these rules — the references are the idealized standard; when they disagree with a production screen, follow the references. Browse the same content visually in the Hub: http://localhost:5174/design-system and http://localhost:5174/design-patterns.

## Run the prototype

\`\`\`bash
cd prototype
VITE_PORT=${port} yarn start
\`\`\`

Or use the Hub at http://localhost:5174 to start/stop it.

## Card cover screenshot

After completing a meaningful UI milestone, refresh this project's card image: use Playwright against the running prototype to capture a **zoomed-in** screenshot of the single most critical UI element of the work — a tight crop on the thing that matters (a drawer, a grid interaction, a chart), never a zoomed-out full page — and save it to \`~/freddy/projects/${slug}/cover.png\` (PNG, roughly 640×300, landscape).

The Hub home page picks this file up automatically as the project's card image and falls back to stock art when it is absent. It lives OUTSIDE \`prototype/\` so it never dirties the branch.

## Working agreement for Claude Code

- All code changes go in \`./prototype/\`. Treat it like a normal proto-base working dir.
- Reference \`./design-system/lofi/round-N/\` when implementing visual work — those wireframes are the source of truth for layout/IA on this project.
- Reference \`./resources/\` for briefs and supporting docs.
- Do NOT edit anything in \`./excalibrr-freddy\` (it's a symlink to a shared sibling).
- When you finish a chunk, commit on branch \`project/${slug}\`. Push only when explicitly asked.
- Build verification: the user runs \`yarn build\` themselves — skip it.
`;
}

export interface VariantClaudeMdInput {
  projectName: string;
  projectSlug: string;
  projectDescription?: string;
  variantName: string;
  variantSlug: string;
  variantDescription?: string;
  label: string;
  parentVersion: string;
  port: number;
  isoDate: string;
}

export function renderVariantClaudeMd(input: VariantClaudeMdInput): string {
  const {
    projectName,
    projectSlug,
    projectDescription,
    variantName,
    variantSlug,
    variantDescription,
    label,
    parentVersion,
    port,
    isoDate,
  } = input;
  const branch = `variant/${projectSlug}/${variantSlug}`;
  const aboutProject = projectDescription?.trim()
    ? `\n**About the project:** ${projectDescription.trim()}\n`
    : "";
  const aboutVariant = variantDescription?.trim()
    ? `\n**Why this variation exists:** ${variantDescription.trim()}\n`
    : "";
  return `# ${projectName} — ${variantName} (variation ${label})

Generated by Project Hub on ${isoDate}.
This is variation \`${label}\` ("${variantName}") of project "${projectName}", forked from version ${parentVersion}.
Branch: \`${branch}\` (worktree of ~/freddy/proto-base)
Dev server URL when running: http://localhost:${port}
${aboutProject}${aboutVariant}
## Project context — it ALL applies here

This worktree is a FULL copy of the project: the entire codebase and its complete
git history up to the fork point (\`git log\` shows everything). Everything about
how "${projectName}" was designed and built — its architecture, conventions,
naming, and intent — applies to this variation unchanged. You are not starting
fresh; you are continuing an existing project on a client-specific branch.

Before doing anything substantial, load the parent project's context:

1. \`~/freddy/projects/${projectSlug}/CLAUDE.md\` — the project's working agreement and paths
2. \`~/freddy/projects/${projectSlug}/README.md\` — what the project is
3. If present in the parent folder: \`project-context.md\`, \`PROJECT_NOTES.md\`,
   \`resources/REFERENCES.md\` — design decisions, session history, references
4. \`git log\` in \`./prototype/\` — how the prototype actually evolved

The ONLY thing that makes this variation different from the mainline is what gets
committed on \`${branch}\` after the fork — typically client-specific data/content.

## Scope — read this first

You are working on ONE variation of the prototype, NOT the project mainline.

- ALL edits happen in \`./prototype/\` — a git worktree on branch \`${branch}\`.
- Do NOT touch the parent project's worktree (\`~/freddy/projects/${projectSlug}/prototype/\`) or any other variation under \`~/freddy/projects/${projectSlug}/variants/\`.
- This variation exists to diverge — typically client-specific data and content. Feature work that should reach every client belongs on the project mainline; flag it for the user instead of building it here.

## Paths

- \`./prototype/\`        — git worktree on \`${branch}\` — edit here
- \`./excalibrr-freddy\`  — symlink to ~/freddy/excalibrr-freddy (do not edit)
- \`~/freddy/projects/${projectSlug}/\` — parent project folder; briefs in \`resources/\`, wireframes in \`design-system/lofi/\` (read-only references)

## Run the prototype

\`\`\`bash
cd prototype
VITE_PORT=${port} yarn start
\`\`\`

Or use the Hub at http://localhost:5174 to start/stop it.

## Design references

UI work follows the vendored Excalibrr references in the Hub repo — component usage from \`${EXCALIBRR_DESIGN_SYSTEM_PATH}/CLAUDE.md\`, layout rules from \`${EXCALIBRR_DESIGN_PATTERNS_PATH}/CLAUDE.md\`.

## Working agreement for Claude Code

- When you finish a chunk, commit on branch \`${branch}\`. Push only when explicitly asked.
- Leave the working tree clean between sessions — the Hub's "Pull from project" and "Promote to mainline" actions refuse to run on a dirty tree.
- Do NOT edit anything in \`./excalibrr-freddy\` (it's a symlink to a shared sibling).
- Build verification: the user runs \`yarn build\` themselves — skip it.
`;
}

export interface RoundClaudeMdInput {
  projectName: string;
  slug: string;
  roundN: number;
  parentRoundN: number; // 0 when this is the first round
  isoDate: string;
}

export function renderRoundClaudeMd(input: RoundClaudeMdInput): string {
  const { projectName, slug, roundN, parentRoundN, isoDate } = input;
  const lofiDir = `~/freddy/projects/${slug}/design-system/lofi`;
  const previousRoundBlock =
    parentRoundN > 0
      ? `## Iterate on the previous round

This is **round ${roundN}**, building on **round ${parentRoundN}**. Round ${parentRoundN} is the base — start there, don't start fresh:

- \`${lofiDir}/round-${parentRoundN}/\` — the previous round's folder
  - \`wireframes/\` — the wireframes you are iterating on
  - \`WIREFRAME-GUIDE.html\` (if present) — its design decisions, changes, and open questions; carry the resolved decisions forward
  - \`brief.md\` / \`CLAUDE.md\` — what that round resolved

Treat round ${roundN} as the next pass: keep what worked, change what the brief calls out.
`
      : `## This is the first round

There is no previous round to build on. Seed round ${roundN} from the kickoff and resources below.
`;
  return `# ${projectName} — Lo-fi round ${roundN}

Generated by Project Hub on ${isoDate}.
This is **round ${roundN}** of the lo-fi wireframe exploration for "${projectName}".
This is a document-centric, static-HTML workspace — there is no dev server and no port. Wireframes open via \`file://\`.

## What this round is

A single sequential pass of the UX${parentRoundN > 0 ? `, iterating on round ${parentRoundN}` : ""}. Build the wireframe(s) for this pass into \`./wireframes/\`, link them from \`./index.html\`, then document the round with \`/wireframe-index\`.

${previousRoundBlock}
## Build wireframes FROM the design system

The shared lo-fi design system is vendored in the Hub repo. Build every wireframe from it — copy its \`wf-\` component markup verbatim, reference \`--wf-\` tokens by name, never invent class names:

- \`${WIREFRAME_DESIGN_SYSTEM_PATH}/\` — start at its \`CLAUDE.md\` → \`DESIGN.md\` → \`reference-guide.html\` (visual index)

## Make the index / guide page WITH /wireframe-index

**This is how you make the round's index page — use the \`/wireframe-index\` skill; never hand-write it.** After building the wireframes, invoke it to generate this round's \`WIREFRAME-GUIDE.html\` — the transparency layer cataloging every screen with round context, *Design Decisions Reflected*, *Changes from Previous Round*, and *Open Questions*.

\`\`\`
/wireframe-index
\`\`\`

- **Primary:** the installed \`/wireframe-index\` skill (present in Cowork / claude.ai desktop) — just run it.
- **Backup:** if the skill isn't installed in this session, the full skill is bundled with this project at \`../wireframe-index-skill/SKILL.md\` (relative to this round folder) — read it and follow it verbatim. It is the canonical guide template.

Either path produces an HTML \`WIREFRAME-GUIDE.html\` (never \`.md\`), so the Hub surfaces it and marks the round **Documented**.

## Context for the "why"

- \`${lofiDir}/KICKOFF.md\` — the lo-fi brief / kickoff notes that seed the exploration
- \`./brief.md\` — what THIS round resolves (from the PM)
- \`./context/\` — drop transcripts/scripts/notes here; \`/wireframe-index\` mines them for rationale
- \`~/freddy/projects/${slug}/resources/\` — project briefs, screenshots, references (read-only)

## Paths

- \`./wireframes/\`          — build the actual wireframe HTML here (source of truth for this round)
- \`./index.html\`           — gallery that links the wireframes (the Launch target)
- \`./brief.md\`             — what this round resolves
- \`./context/\`             — dropped inputs mined for the "why"
- \`./WIREFRAME-GUIDE.html\` — generated by \`/wireframe-index\` (do not hand-write)
- \`./options/\`             — parallel branch-options for this round (Direction A/B/C), if any

## Working agreement for Claude Code

- Build wireframes into \`./wireframes/\` and keep \`./index.html\` linking them.
- Lo-fi is static HTML only — do NOT start a server or wire up a build.
- When directions diverge, the Hub spawns **branch-options** as sibling folders under \`./options/\`; explore them in parallel, then one is chosen and folds forward into the next round.
- After building, run \`/wireframe-index\` to document the round.
`;
}

export interface OptionClaudeMdInput {
  projectName: string;
  slug: string;
  roundN: number;
  optionName: string;
  optionSlug: string;
  isoDate: string;
}

export function renderOptionClaudeMd(input: OptionClaudeMdInput): string {
  const { projectName, slug, roundN, optionName, optionSlug, isoDate } = input;
  const lofiDir = `~/freddy/projects/${slug}/design-system/lofi`;
  return `# ${projectName} — Round ${roundN}, branch-option "${optionName}"

Generated by Project Hub on ${isoDate}.
This is a **parallel branch-option** ("${optionName}", slug \`${optionSlug}\`) explored off **round ${roundN}**.
Branch-options are sibling folders, NOT git branches. They are compared side by side; one is chosen and folds forward into the next round, the others stay as a record.

## What this option is

One alternative direction for round ${roundN}. Build its wireframe(s) into \`./wireframes/\` and link them from \`./index.html\`, so it can be compared against the other options.

## Parent round — your base

- \`${lofiDir}/round-${roundN}/\` — the round this option branches from
  - \`CLAUDE.md\` — the round working agreement (design system + \`/wireframe-index\` pointers apply here too)
  - \`wireframes/\` — the mainline wireframes for the round
  - \`WIREFRAME-GUIDE.html\` (if present) — round decisions and open questions

## Build FROM the design system

Build from the shared lo-fi design system, same as the parent round — copy \`wf-\` markup verbatim, reference \`--wf-\` tokens by name:

- \`${WIREFRAME_DESIGN_SYSTEM_PATH}/\` — start at \`CLAUDE.md\` → \`DESIGN.md\` → \`reference-guide.html\`

## Paths

- \`./wireframes/\` — build this option's wireframe HTML here
- \`./index.html\`  — gallery linking this option's wireframes

## Working agreement for Claude Code

- This is one of several parallel directions — focus only on THIS option's folder.
- Static HTML only — no server, no build.
- When the option is chosen, its wireframes fold forward into the next round's mainline.
`;
}

export function renderProjectReadme(input: ClaudeMdInput, description?: string): string {
  const { name, slug, port } = input;
  const desc = description?.trim() ? `\n${description.trim()}\n` : "";
  return `# ${name}
${desc}
Slug: \`${slug}\`
Branch: \`project/${slug}\`
Prototype dev port: ${port}

See \`CLAUDE.md\` for the working agreement.

## Quick start

\`\`\`bash
cd prototype
VITE_PORT=${port} yarn start
\`\`\`
`;
}
