import type { MetadataListResponseItem } from '@api/globalTypes'
import { dateFormat } from '@components/TheArmory/helpers'
import {
  CreateSpecialOfferRequest,
  IndexOfferMetaData,
  IndexPricingFormData,
  IndexPricingInfo,
} from '@modules/Dashboard/SpecialOffers/Api/types.schema'
import { convertComponentsToFormula } from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Util/indexConfigHelpers'
import { step1Fields, step2Fields } from '@modules/Dashboard/SpecialOffers/utils/Constants/FormConstants'
import { getDefaultStartTime } from '@modules/Dashboard/SpecialOffers/utils/Constants/TimingWindowConstants'
import { getTimezoneIana } from '@modules/Dashboard/SpecialOffers/utils/Utils/TimingWindowHelpers'
import { getAutoGeneratedPricingDisplayText } from '@modules/FormulaTemplates/Util/formHelpers'
import type { Dayjs } from '@utils/dayjs'
import dayjs from '@utils/dayjs'
import type { FormInstance } from 'antd'
export interface createPayloadFromValuesProps {
  values: any
  indexPricingData?: IndexPricingFormData
  formulaMetadata?: IndexOfferMetaData
  validTimeZones?: MetadataListResponseItem[]
}
export function createPayloadFromValues({
  values,
  indexPricingData,
  formulaMetadata,
  validTimeZones,
}: createPayloadFromValuesProps): CreateSpecialOfferRequest {
  const tradeEntrySetupIds =
    typeof values.ProductLocation === 'number' ? [values.ProductLocation] : values.ProductLocation

  const timezone = getTimezoneIana(values.TimeZoneId, validTimeZones)
  const startNowTime = getDefaultStartTime(timezone)

  const InvitationTriggerDateTimeTZ = values.SendInvitesOnCreate
    ? constructDateTimeString(startNowTime, startNowTime)
    : constructDateTimeString(values.InviteTriggerDate, values.InviteTriggerTime)

  let indexPricingInfo: IndexPricingInfo | undefined
  if (indexPricingData) {
    const formula = convertComponentsToFormula(indexPricingData)
    indexPricingInfo = {
      ProductId: indexPricingData.ProductId,
      LocationId: indexPricingData.LocationId,
      EffectiveTime: indexPricingData.PricingEffectiveTimes,
      WeekendRule: indexPricingData.PricingWeekendBehavior,
      HolidayRule: indexPricingData.PricingHolidayBehavior,
      AdditionalFreetextTerms: indexPricingData.AdditionalFreetextTerms,
      PricingDisplayText:
        indexPricingData.PricingDisplayText ||
        getAutoGeneratedPricingDisplayText(indexPricingData.formulaComponents, formulaMetadata),
      ContractDifferential: indexPricingData.FormulaDifferential ?? 0,
      Formula: formula,
      StartDate: values.VisibilityStartNow
        ? constructDateTimeString(startNowTime, startNowTime)
        : constructDateTimeString(values.VisibilityWindowStartDate, values.VisibilityWindowStartTime),
      EndDate: constructDateTimeString(values.VisibilityWindowEndDate, values.VisibilityWindowEndTime),
    }
  }

  return {
    SpecialOfferTemplateId: values.SpecialOfferTemplateId,
    MinimumVolumePerOrder: values.MinimumVolumePerOrder,
    MaximumVolumePerOrder: values.MaximumVolumePerOrder,
    VolumeIncrement: values.VolumeIncrement,
    TotalVolume: values.TotalVolume,
    ReservePrice: indexPricingData?.ReservePrice ?? values.ReservePrice ?? undefined,
    FixedPrice: values.ReservePrice || undefined,
    VisibilityStartDateTime: values.VisibilityStartNow
      ? constructDateTimeString(startNowTime, startNowTime)
      : constructDateTimeString(values.VisibilityWindowStartDate, values.VisibilityWindowStartTime),
    VisibilityEndDateTime: constructDateTimeString(values.VisibilityWindowEndDate, values.VisibilityWindowEndTime),
    OrderEffectiveStartDateTime: values.PickupStartNow
      ? constructDateTimeString(startNowTime, startNowTime)
      : constructDateTimeString(values.PickupWindowStartDate, values.PickupWindowStartTime),
    OrderEffectiveEndDateTime: constructDateTimeString(values.PickupWindowEndDate, values.PickupWindowEndTime),
    CounterPartyIds: values.CounterPartyIds,
    TradeEntrySetupIds: tradeEntrySetupIds,
    InvitationTriggerDateTimeTZ,
    TimeZoneId: values.TimeZoneId,
    SendInvitesOnCreate: values.SendInvitesOnCreate ?? false,
    IndexPricingInfo: indexPricingInfo,
  }
}

function constructDateTimeString(date: Dayjs, time?: Dayjs): string {
  return dayjs(date)
    .set('hour', time ? time.get('hour') : 0)
    .set('minute', time ? time.get('minute') : 0)
    .set('second', 0)
    .format(dateFormat.ISO)
}
export function validateFormFields({
  form,
  goNext,
  currentStep,
  setShowIndexError,
  isIndexPricing,
}: {
  form: FormInstance
  goNext: () => void
  currentStep: number
  setShowIndexError: React.Dispatch<React.SetStateAction<boolean>>
  isIndexPricing: boolean
}) {
  const fieldsToValidate = isIndexPricing ? step1Fields.concat('IndexPrice') : step1Fields
  if (currentStep === 1) {
    form
      .validateFields(['ProductLocation'])
      .then(() => {
        form
          .validateFields(fieldsToValidate)
          .then((e) => {
            setShowIndexError(false)
            goNext()
          })
          .catch(({ values, errorFields }) => {
            if (errorFields?.length && isIndexPricing) {
              setShowIndexError(errorFields?.find((f) => f.name[0] === 'IndexPrice')?.errors?.length > 0)
            }
          })
      })
      .catch(() => {})
  }
  if (currentStep === 2) {
    form.validateFields(step2Fields).then(() => goNext())
  }
}
