import { RiseOutlined } from '@ant-design/icons'
import { GraviButton, Texto, Vertical } from '@gravitate-js/excalibrr'
import { useFormDefaults } from '@hooks/useFormDefaults'
import {
  IndexOfferFormulaComponent,
  IndexPricingFormData,
  SpecialOfferMetadataResponseData,
} from '@modules/Dashboard/SpecialOffers/Api/types.schema'
import { AdditionalTerms } from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Components/ConfigureIndexPrice/Components/AdditionalTerms'
import { ConfiguredPriceDisplay } from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Components/ConfigureIndexPrice/Components/ConfiguredPriceDisplay'
import { DrawerFooter } from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Components/ConfigureIndexPrice/Components/DrawerFooter'
import { DrawerTitle } from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Components/ConfigureIndexPrice/Components/DrawerTitle'
import { FormulaComponentBuilder } from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Components/ConfigureIndexPrice/Components/FormulaComponentBuilder'
import { FormulaDiff } from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Components/ConfigureIndexPrice/Components/FormulaDiff'
import { ReferenceData } from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Components/ConfigureIndexPrice/Components/ReferenceData'
import { generateIndexOfferDisplayName } from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Components/ConfigureIndexPrice/Utils/IndexFormHelpers'
import {
  getTemplateDetailsFromComponents,
  mapIndexMetadataToSelectorMetadata,
  mapTemplateToComponents,
  mapToFormulaMetadata,
} from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Components/ConfigureIndexPrice/Utils/TemplateHelpers'
import { OSPFormulaTemplateEndpoints } from '@modules/FormulaTemplates/Api/FormulaTemplateEndpoints'
import { FormulaTemplateDetails } from '@modules/FormulaTemplates/Api/types.schema'
import { PricingDisplaySection } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/PricingDisplaySection'
import { FormulaTemplateDrawer } from '@modules/FormulaTemplates/Components/CreateEditDrawer/FormulaTemplateDrawer'
import { FormulaTemplateSelector } from '@modules/FormulaTemplates/Components/FormulaTemplateSelector/FormulaTemplateSelector'
import { getAutoGeneratedPricingDisplayText } from '@modules/FormulaTemplates/Util/formHelpers'
import type { FormInstance } from 'antd'
import { Drawer, Form } from 'antd'
import { MutableRefObject, useEffect, useMemo, useState } from 'react'

export interface ConfigureIndexPriceProps {
  metadata: SpecialOfferMetadataResponseData | undefined
  onSaveIndexPricing: (data: IndexPricingFormData | null) => void
  savedIndexData?: IndexPricingFormData | null
  isAuction: boolean
  idRef: MutableRefObject<number>
  showIndexError: boolean
  setShowIndexError: React.Dispatch<React.SetStateAction<boolean>>
  formulaForm: FormInstance
  offerForm: FormInstance
  selectedProductLocation: number
}

export function ConfigureIndexPrice({
  metadata,
  onSaveIndexPricing,
  savedIndexData,
  isAuction,
  idRef,
  showIndexError,
  setShowIndexError,
  formulaForm,
  offerForm,
  selectedProductLocation,
}: ConfigureIndexPriceProps) {
  const [isOpen, setIsOpen] = useState(false)
  const [isTemplateDrawerVisible, setIsTemplateDrawerVisible] = useState(false)
  const [templateToCreate, setTemplateToCreate] = useState<Partial<FormulaTemplateDetails> | null>(null)
  const [formulaComponents, setFormulaComponents] = useState<IndexOfferFormulaComponent[]>([])
  const [isChoosingTemplate, setIsChoosingTemplate] = useState(false)
  const [showCustomDisplayName, setShowCustomDisplayName] = useState(false)

  const stickyFields = useMemo(
    () => ['PricingEffectiveTimes', 'PricingWeekendBehavior', 'PricingHolidayBehavior'] as const,
    []
  )
  const { savedDefaults, updateDefaults } = useFormDefaults<IndexPricingFormData>('indexPricing', [...stickyFields])

  const selectorMetadata = useMemo(
    () => mapIndexMetadataToSelectorMetadata(metadata?.IndexOfferMetaData),
    [metadata?.IndexOfferMetaData]
  )

  const uomSymbol = useMemo(() => {
    const selection = metadata?.ProductLocationSelections?.find((s) => s.TradeEntrySetupId == selectedProductLocation)
    return selection?.UnitOfMeasureSymbol ?? defaultUnitOfMeasureSymbol
  }, [metadata?.ProductLocationSelections, selectedProductLocation])

  const onOpen = () => {
    const selection = metadata?.ProductLocationSelections?.find((s) => s.TradeEntrySetupId == selectedProductLocation)
    const LocationId = selection ? selection.LocationId.toString() : undefined
    const ProductId = selection ? selection.ProductId.toString() : undefined

    if (savedIndexData) {
      formulaForm.setFieldsValue({ ...savedIndexData, ProductId, LocationId })
      setFormulaComponents(savedIndexData.formulaComponents)
    } else {
      formulaForm.setFieldsValue({ ProductId, LocationId, ...savedDefaults })
      setFormulaComponents([])
    }
  }

  useEffect(() => {
    if (isOpen) onOpen()
  }, [isOpen, savedIndexData])

  // Render the Configured Price summary when savedIndexData arrives before the user opens the drawer.
  useEffect(() => {
    if (formulaComponents.length === 0 && (savedIndexData?.formulaComponents?.length ?? 0) > 0) {
      setFormulaComponents(savedIndexData!.formulaComponents)
    }
  }, [savedIndexData])

  const formulaMetadata = useMemo(
    () => mapToFormulaMetadata(metadata?.IndexOfferMetaData),
    [metadata?.IndexOfferMetaData]
  )

  const onFinish = (values: IndexPricingFormData) => {
    const pricingText =
      showCustomDisplayName && values.PricingDisplayText ? values.PricingDisplayText : autoGeneratedPricingText
    if (pricingText.length > 1000) {
      return
    }

    const indexData: IndexPricingFormData = {
      ...values,
      formulaComponents: formulaComponents.map((v) => {
        return v.DisplayName ? v : { ...v, DisplayName: generateIndexOfferDisplayName(v, metadata?.IndexOfferMetaData) }
      }),
      FormulaDifferential: values.FormulaDifferential ?? 0,
      PricingDisplayText:
        showCustomDisplayName && values.PricingDisplayText ? values.PricingDisplayText : autoGeneratedPricingText,
    }
    onSaveIndexPricing?.(indexData)
    setShowIndexError(false)
    offerForm.setFieldsValue({
      ReservePrice: values.ReservePrice,
    })
    setIsOpen(false)
  }

  const handleClose = () => {
    setIsOpen(false)
    setFormulaComponents(savedIndexData?.formulaComponents || [])
    formulaForm.resetFields()
    setShowCustomDisplayName(false)
  }

  const autoGeneratedPricingText = useMemo(() => {
    if (!formulaComponents?.length) return 'No components added yet'
    return getAutoGeneratedPricingDisplayText(formulaComponents, formulaMetadata)
  }, [formulaComponents, formulaMetadata])

  useEffect(() => {
    if (!isOpen) return
    if (savedIndexData?.PricingDisplayText) {
      const savedAutoText = getAutoGeneratedPricingDisplayText(savedIndexData.formulaComponents, formulaMetadata)
      setShowCustomDisplayName(savedIndexData.PricingDisplayText !== savedAutoText)
    } else {
      setShowCustomDisplayName(false)
    }
  }, [isOpen, savedIndexData, formulaMetadata])

  const viewTemplateChooser = () => {
    setIsChoosingTemplate(true)
  }

  const onTemplateSelect = (selectedTemplate: FormulaTemplateDetails) => {
    const newComponents = mapTemplateToComponents(selectedTemplate, idRef, metadata?.IndexOfferMetaData)
    const updatedComponents = [...formulaComponents, ...newComponents]
    setFormulaComponents(updatedComponents)
    formulaForm.setFieldsValue({ FormulaTemplateVariables: updatedComponents })

    if (!showCustomDisplayName && selectedTemplate.PricingDisplayText) {
      const autoText = getAutoGeneratedPricingDisplayText(updatedComponents, formulaMetadata)
      const isCustom = selectedTemplate.PricingDisplayText !== autoText
      setShowCustomDisplayName(isCustom)
      if (isCustom) {
        formulaForm.setFieldsValue({ PricingDisplayText: selectedTemplate.PricingDisplayText })
      }
    }

    setIsChoosingTemplate(false)
  }

  const handleSaveAsTemplate = () => {
    const templateDetails = getTemplateDetailsFromComponents(formulaComponents, formulaForm)
    setTemplateToCreate(templateDetails)
    setIsTemplateDrawerVisible(true)
  }
  return (
    <>
      <Vertical>
        <Texto category={'h4'} className={'text-18'}>
          Set Index Price
        </Texto>
        <Texto className={'mb-4 text-14'}>Configure index based pricing for your offer</Texto>
      </Vertical>

      {savedIndexData && formulaComponents.length > 0 ? (
        <ConfiguredPriceDisplay
          savedIndexData={savedIndexData}
          onSaveIndexPricing={onSaveIndexPricing}
          formula={savedIndexData.PricingDisplayText || autoGeneratedPricingText}
          openConfig={setIsOpen}
          isAuction={isAuction}
          metadata={metadata}
          uomSymbol={uomSymbol}
        />
      ) : (
        <Vertical
          gap={10}
          className={'bordered border-radius-10 p-4'}
          style={showIndexError ? { borderColor: ' var(--theme-error) !important' } : {}}
          verticalCenter
          horizontalCenter
        >
          <RiseOutlined style={{ fontSize: '50px', color: 'var(--gray-500)' }} />
          <Texto category={'h5'}>No Index Price Configured</Texto>
          <Texto className={'text-14'}>Set up an index based pricing strategy</Texto>
          <GraviButton
            className={'mt-2'}
            buttonText={
              <Texto weight={'normal'} className={'text-14'}>
                Build Index Price
              </Texto>
            }
            onClick={() => setIsOpen(true)}
          />
        </Vertical>
      )}

      <Drawer
        className={'create-index-drawer'}
        title={<DrawerTitle handleClose={handleClose} />}
        open={isOpen}
        onClose={handleClose}
        placement={'bottom'}
        height={'85vh'}
        closable={false}
        footer={!isChoosingTemplate && <DrawerFooter form={formulaForm} handleClose={handleClose} />}
        styles={{ body: isChoosingTemplate ? { backgroundColor: 'var(--bg-2)', paddingTop: 0 } : {} }}
      >
        {isChoosingTemplate && selectorMetadata ? (
          <FormulaTemplateSelector
            isChoosingTemplate={isChoosingTemplate}
            setIsChoosingTemplate={setIsChoosingTemplate}
            metadata={selectorMetadata}
            onTemplateSelect={onTemplateSelect}
            manageTemplatesLink={'/Admin/FormulaTemplates'}
          />
        ) : (
          <Form onFinish={onFinish} form={formulaForm} layout={'vertical'} onValuesChange={updateDefaults}>
            <Vertical gap={10}>
              <ReferenceData metadata={metadata} selectedProductLocation={selectedProductLocation} />
              <PricingDisplaySection
                pricingDisplayText={autoGeneratedPricingText}
                showCustomInput={showCustomDisplayName}
                setShowCustomInput={setShowCustomDisplayName}
                form={formulaForm}
              />
              <FormulaComponentBuilder
                metadata={metadata}
                formulaComponents={formulaComponents}
                setFormulaComponents={setFormulaComponents}
                form={formulaForm}
                addTemplate={viewTemplateChooser}
                saveAsTemplate={handleSaveAsTemplate}
                idRef={idRef}
              />
              <AdditionalTerms metadata={metadata} />
              <FormulaDiff isAuction={isAuction} />
            </Vertical>
          </Form>
        )}
      </Drawer>
      <FormulaTemplateDrawer
        viewMode='Create'
        isDrawerVisible={isTemplateDrawerVisible}
        setIsDrawerVisible={setIsTemplateDrawerVisible}
        selectedTemplate={templateToCreate}
        setSelectedTemplate={setTemplateToCreate}
        existingTemplates={metadata?.IndexOfferMetaData?.FormulaTemplates}
        endpoints={OSPFormulaTemplateEndpoints}
        onSaveInvalidateKey='MarketPlatform/SpecialOfferAdmin/GetMetadata'
      />
    </>
  )
}
