import { CopyOutlined } from '@ant-design/icons'
import { Texto } from '@gravitate-js/excalibrr'
import { Button, Input, message } from 'antd'

interface AutoGeneratedFormulaProps {
  formula: string
}

export function AutoGeneratedFormula({ formula }: AutoGeneratedFormulaProps) {
  const handleCopy = () => {
    navigator.clipboard.writeText(formula).then(
      () => {
        message.success('Formula copied to clipboard')
      },
      () => {
        message.error('Failed to copy formula')
      }
    )
  }

  return (
    <>
      <Texto>Auto-Generated</Texto>
      <div style={{ position: 'relative' }}>
        <Input.TextArea
          id='autoGeneratedFormulaInput'
          disabled
          value={formula}
          className={'p-4 border-radius-4'}
          style={{
            fontSize: '13px',
            fontFamily: 'monospace',
            borderRadius: '3px',
            color: '#595959',
            resize: 'none',
            pointerEvents: 'none',
            paddingRight: '32px',
          }}
          autoSize={{ minRows: 1 }}
        />
        <Button
          icon={<CopyOutlined />}
          onClick={handleCopy}
          type='text'
          size='middle'
          title='Copy to clipboard'
          style={{
            position: 'absolute',
            top: '4px',
            right: '4px',
            zIndex: 1,
            pointerEvents: 'auto',
          }}
          aria-label='Copy to clipboard'
        />
      </div>
    </>
  )
}
