import { IndexOfferFormulaComponent, IndexOfferMetaData } from '@modules/Dashboard/SpecialOffers/Api/types.schema'
import { generateIndexOfferDisplayName } from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Components/ConfigureIndexPrice/Components/IndexOfferComponentsColumnDefs'
import { TemplateSelectorMetadata } from '@modules/FormulaTemplates/Api/templateSelectorTypes'
import {
  FormulaTemplateDetails,
  FormulaTemplateMetadata,
  FormulaTemplateVariable,
} from '@modules/FormulaTemplates/Api/types.schema'
import { FormInstance } from 'antd'

export function mapIndexMetadataToSelectorMetadata(
  indexMeta: IndexOfferMetaData | undefined
): TemplateSelectorMetadata | undefined {
  if (!indexMeta) return undefined

  // Flatten all publisher price types into a single array
  const allPriceTypes = Object.values(indexMeta.PublisherPriceTypes || {}).flat()

  return {
    ProductList: indexMeta.Products,
    LocationList: indexMeta.Locations,
    PriceTypeList: allPriceTypes,
    PricePublisherList: indexMeta.PricePublishers,
    PriceInstrumentList: indexMeta.PriceInstruments,
    TradePriceValuationRuleList: indexMeta.TradePriceValuationRules,
    FormulaTemplates: indexMeta.FormulaTemplates || [],
  }
}

export function mapTemplateVariableToIndexComponent(
  variable: FormulaTemplateVariable,
  id: number,
  metadata?: IndexOfferMetaData
): IndexOfferFormulaComponent {
  const component: IndexOfferFormulaComponent = {
    Percentage: variable.Percentage ?? null,
    PricePublisherId: variable.PricePublisherId ?? null,
    PriceInstrumentId: variable.PriceInstrumentId ?? null,
    PriceValuationRuleId: variable.PriceValuationRuleId ?? null,
    PriceTypeCvId: variable.PriceTypeCvId ?? null,
    DisplayName: variable.DisplayName || '',
    IdForGrid: id,
    isDisplayNameCustomized: false,
  }

  // Determine if the display name is custom by comparing to auto-generated
  const autoGeneratedName = generateIndexOfferDisplayName(component, metadata)
  const isCustom = !!variable.DisplayName && variable.DisplayName !== autoGeneratedName
  component.isDisplayNameCustomized = isCustom

  return component
}

export function mapTemplateToComponents(
  template: FormulaTemplateDetails,
  idRef: React.MutableRefObject<number>,
  metadata?: IndexOfferMetaData
): IndexOfferFormulaComponent[] {
  return template.FormulaTemplateVariables.map((variable) =>
    mapTemplateVariableToIndexComponent(variable, idRef.current++, metadata)
  )
}

export function mapIndexComponentToTemplateVariable(component: IndexOfferFormulaComponent): FormulaTemplateVariable {
  return {
    Percentage: component.Percentage,
    PricePublisherId: component.PricePublisherId,
    PriceInstrumentId: component.PriceInstrumentId,
    PriceValuationRuleId: component.PriceValuationRuleId,
    PriceTypeCvId: component.PriceTypeCvId,
    DisplayName: component.DisplayName || null,
    Differential: component.Differential,
    IsPlaceholder: false,
    IsRequired: true,
    IsVisible: true,
  }
}

export function getTemplateDetailsFromComponents(
  components: IndexOfferFormulaComponent[],
  form: FormInstance
): Partial<FormulaTemplateDetails> {
  const formValues = form.getFieldsValue()

  // Map components to template variables with temporary IDs for the grid
  const templateVariables = components.map((component, index) => ({
    ...mapIndexComponentToTemplateVariable(component),
    IdForGrid: `new-${index}`,
  }))

  const applicableProducts = formValues.ProductId ? [{ ProductId: formValues.ProductId }] : []
  const applicableLocations = formValues.LocationId ? [{ LocationId: formValues.LocationId }] : []

  return {
    FormulaTemplateId: undefined,
    Name: undefined,
    Formula: null,
    FormulaTemplateVariables: templateVariables,
    FormulaTemplateApplicableProducts: applicableProducts,
    FormulaTemplateApplicableLocations: applicableLocations,
    FormulaTemplateCategoryId: null,
    FormulaTemplateCategoryDisplay: null,
    CreatedByCredentialId: undefined,
    CreatedDateTime: null,
    IsActive: true,
    IsSystemCalculation: false,
    IsVisible: true,
    MarkerId: null,
    ParserType: null,
  }
}

export function mapToFormulaMetadata(
  indexMeta: IndexOfferMetaData | undefined
): Partial<FormulaTemplateMetadata> | undefined {
  if (!indexMeta) return undefined

  const allPriceTypes = Object.values(indexMeta.PublisherPriceTypes || {}).flat()

  return {
    Publishers: indexMeta.PricePublishers,
    Instruments: indexMeta.PriceInstruments,
    DateRules: indexMeta.TradePriceValuationRules,
    PriceTypes: allPriceTypes,
    PublisherPriceTypes: indexMeta.PublisherPriceTypes,
  }
}
