import { MetadataListResponseItem } from '@api/globalTypes'
import { IndexOfferFormulaComponent, IndexOfferMetaData } from '@modules/Dashboard/SpecialOffers/Api/types.schema'
import { TemplateSelectorMetadata } from '@modules/FormulaTemplates/Api/templateSelectorTypes'
import {
  FormulaTemplateDetails,
  FormulaTemplateMetadata,
  FormulaTemplateVariable,
} from '@modules/FormulaTemplates/Api/types.schema'
import { FormInstance } from 'antd'
import { generateIndexOfferDisplayName } from '@modules/Dashboard/SpecialOffers/Components/CreateNew/Components/ConfigureIndexPrice/Utils/IndexFormHelpers'

function getUniquePriceTypes(
  publisherPriceTypes: Record<string, MetadataListResponseItem[]> | undefined
): MetadataListResponseItem[] {
  return [
    ...new Map(
      Object.values(publisherPriceTypes || {})
        .flat()
        .map((pt) => [pt.Value, pt])
    ).values(),
  ]
}

export function mapIndexMetadataToSelectorMetadata(
  indexMeta: IndexOfferMetaData | undefined
): TemplateSelectorMetadata | undefined {
  if (!indexMeta) return undefined

  return {
    ProductList: indexMeta.Products,
    LocationList: indexMeta.Locations,
    PriceTypeList: getUniquePriceTypes(indexMeta.PublisherPriceTypes),
    PricePublisherList: indexMeta.PricePublishers,
    PriceInstrumentList: indexMeta.PriceInstruments,
    TradePriceValuationRuleList: indexMeta.TradePriceValuationRules,
    FormulaTemplates: indexMeta.FormulaTemplates || [],
  }
}

function mapTemplateVariableToIndexComponent(
  variable: FormulaTemplateVariable,
  id: number,
  metadata?: IndexOfferMetaData
): IndexOfferFormulaComponent {
  const component: IndexOfferFormulaComponent = {
    Percentage: variable.Percentage ?? null,
    PricePublisherId: variable.PricePublisherId ?? null,
    PriceInstrumentId: variable.PriceInstrumentId ?? null,
    PriceValuationRuleId: variable.PriceValuationRuleId ?? null,
    PriceTypeCvId: variable.PriceTypeCvId ?? null,
    Differential: variable.Differential ?? null,
    DisplayName: null,
    IdForGrid: id,
  }

  // If display name is custom (doesn't match auto-generated), keep it; otherwise leave null for auto-generation
  const autoGeneratedName = generateIndexOfferDisplayName(component, metadata)
  if (variable.DisplayName && variable.DisplayName !== autoGeneratedName) {
    component.DisplayName = variable.DisplayName
  }

  return component
}

export function mapTemplateToComponents(
  template: FormulaTemplateDetails,
  idRef: React.MutableRefObject<number>,
  metadata?: IndexOfferMetaData
): IndexOfferFormulaComponent[] {
  return template.FormulaTemplateVariables.map((variable) =>
    mapTemplateVariableToIndexComponent(variable, idRef.current++, metadata)
  )
}

function mapIndexComponentToTemplateVariable(component: IndexOfferFormulaComponent): FormulaTemplateVariable {
  return {
    Percentage: component.Percentage,
    PricePublisherId: component.PricePublisherId,
    PriceInstrumentId: component.PriceInstrumentId,
    PriceValuationRuleId: component.PriceValuationRuleId,
    PriceTypeCvId: component.PriceTypeCvId,
    DisplayName: component.DisplayName || null,
    IsPlaceholder: false,
    IsRequired: true,
    IsVisible: true,
  }
}

export function getTemplateDetailsFromComponents(
  components: IndexOfferFormulaComponent[],
  form: FormInstance
): Partial<FormulaTemplateDetails> {
  const formValues = form.getFieldsValue()

  // Map components to template variables with temporary IDs for the grid
  const templateVariables = components.map((component, index) => ({
    ...mapIndexComponentToTemplateVariable(component),
    IdForGrid: `new-${index}`,
  }))

  const applicableProducts = formValues.ProductId ? [{ ProductId: formValues.ProductId }] : []
  const applicableLocations = formValues.LocationId ? [{ LocationId: formValues.LocationId }] : []

  return {
    FormulaTemplateId: undefined,
    Name: undefined,
    FormulaTemplateVariables: templateVariables,
    FormulaTemplateApplicableProducts: applicableProducts,
    FormulaTemplateApplicableLocations: applicableLocations,
    FormulaTemplateCategoryId: null,
    FormulaTemplateCategoryDisplay: null,
    CreatedByCredentialId: undefined,
    CreatedDateTime: null,
    IsActive: true,
    IsSystemCalculation: false,
    IsVisible: true,
    MarkerId: null,
    ParserType: null,
    PricingDisplayText: formValues.PricingDisplayText || null,
  }
}

export function mapToFormulaMetadata(
  indexMeta: IndexOfferMetaData | undefined
): Partial<FormulaTemplateMetadata> | undefined {
  if (!indexMeta) return undefined

  return {
    Publishers: indexMeta.PricePublishers,
    Instruments: indexMeta.PriceInstruments,
    DateRules: indexMeta.TradePriceValuationRules,
    PriceTypes: getUniquePriceTypes(indexMeta.PublisherPriceTypes),
    PublisherPriceTypes: indexMeta.PublisherPriceTypes,
  }
}
