import { Vertical } from '@gravitate-js/excalibrr'
import { AutoGeneratedFormula } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/AutoGeneratedFormula'
import { CustomFormulaName } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/CustomFormulaName'
import { SectionTitle } from '@modules/FormulaTemplates/Util/formHelpers'
import { Checkbox } from 'antd'

export function Formula({ formula, showCustomInput, setShowCustomInput }) {
  return (
    <>
      <SectionTitle title={'Formula'} />
      <Vertical className='mb-5 gap-10' style={{ width: '100%' }}>
        <AutoGeneratedFormula formula={formula} />

        <Checkbox
          onChange={(value) => {
            setShowCustomInput(value.target.checked)
          }}
          checked={showCustomInput}
        >
          Custom Formula Name
        </Checkbox>

        {showCustomInput && (
          <CustomFormulaName
            title={'Custom Formula Name (Customer-Facing)'}
            placeholder={'Enter custom formula name'}
            formItemName={'Formula'}
          />
        )}
      </Vertical>
    </>
  )
}
