export const blankFormulaPrice = (varName?: string) => ({
  AllowMultiOrigin: null,
  FormulaId: 0,
  FormulaVariableId: 0,
  FormulaVariableTemplateId: 0,
  CounterPartyMatchTypeCvId: null,
  CreatedByCredentialId: null,
  CreatedDateTime: new Date(),
  DependentFormulaId: null,
  Differential: null,
  DisplayName: '',
  FixedValue: null,
  IsRequired: true,
  IsSystemVariable: true,
  IsTemplateVariable: null,
  IsVisible: false,
  Percentage: 100,
  PriceInstrumentId: null,
  PriceInstrumentName: null,
  PricePublisherId: null,
  PricePublisherName: null,
  PriceTypeCvId: null,
  PriceValuationRuleId: null,
  PriceValuationRuleImplementation: null,
  PriceValuationRuleName: null,
  PriceValuationRuleSourceId: null,
  SpecificLocationId: null,
  SpecificProductId: null,
  SystemDataType: null,
  TradeDateRuleCvId: null,
  UOMConversionOverride: null,
  ValueEffectiveDateRuleCvId: null,
  ValueSourceCvId: null,
  VariableName: varName ?? '',
})
