import { Texto } from '@gravitate-js/excalibrr'
import { FormulaVariable } from '@modules/ContractManagement/api/types.schema'
import {
  FormulaTemplateDetails,
  FormulaTemplateMetadata,
  FormulaTemplateVariable,
} from '@modules/FormulaTemplates/Api/types.schema'
import { FormulaComponentRow, placeholderText, ViewMode } from '@modules/FormulaTemplates/Util/formConstants'
import { isDefinedAndNotNull } from '@utils/index'

export function SectionTitle({ title }: { title: string }) {
  return (
    <Texto weight={'bold'} textTransform={'uppercase'} className={'mb-4'}>
      {title}
    </Texto>
  )
}

export function placeholderCellStyle(value: unknown) {
  if (!isDefinedAndNotNull(value)) {
    return 'placeholder-cell placeholder'
  }
  return ''
}

export function generateVariableDisplayName(
  component: FormulaComponentRow,
  metadata?: Partial<FormulaTemplateMetadata>
): string {
  const percent = isDefinedAndNotNull(component.Percentage) ? `${component.Percentage}%` : placeholderText['Percentage']
  const publisher = isDefinedAndNotNull(component.PricePublisherId)
    ? metadata?.Publishers?.find((item) => item.Value === component.PricePublisherId?.toString())?.Text
    : placeholderText['PricePublisherId']
  const instrument = isDefinedAndNotNull(component.PriceInstrumentId)
    ? metadata?.Instruments?.find((item) => item.Value === component.PriceInstrumentId?.toString())?.Text
    : placeholderText['PriceInstrumentId']
  const type = isDefinedAndNotNull(component.PriceTypeCvId)
    ? metadata?.PriceTypes?.find((item) => item.Value === component.PriceTypeCvId?.toString())?.Text
    : placeholderText['PriceTypeCvId']
  const dateRule = isDefinedAndNotNull(component.PriceValuationRuleId)
    ? metadata?.DateRules?.find((item) => item.Value === component.PriceValuationRuleId?.toString())?.Text
    : placeholderText['PriceValuationRuleId']
  const differential =
    isDefinedAndNotNull(component.Differential) && component.Differential !== 0
      ? `${component.Differential >= 0 ? '+' : ''}${component.Differential}`
      : null

  const baseName = `${percent} ${publisher} ${instrument} ${dateRule} ${type}`
  return differential ? `${baseName} ${differential}` : baseName
}

function getIdValue(id?: number | string | null) {
  if (isDefinedAndNotNull(id)) {
    if (typeof id === 'string') return parseInt(id)
    return id
  } else return null
}

export function getPayload({
  values,
  formulaComponents,
  selectedTemplate,
  formula,
  viewMode,
  metadata,
}: {
  values: FormulaTemplateDetails
  formulaComponents: FormulaComponentRow[]
  selectedTemplate: Partial<FormulaTemplateDetails> | null
  formula?: string | null
  viewMode: ViewMode
  metadata?: FormulaTemplateMetadata
}): Partial<FormulaTemplateDetails> {
  const formulaTemplateVariables = formulaComponents.map((component, index) => ({
    VariableName: component.VariableName || `var_${index + 1}`,
    Percentage: component.Percentage ?? null,
    PricePublisherId: getIdValue(component.PricePublisherId),
    PriceInstrumentId: getIdValue(component.PriceInstrumentId),
    PriceValuationRuleId: getIdValue(component.PriceValuationRuleId),
    PriceTypeCvId: getIdValue(component.PriceTypeCvId),
    DisplayName: component.DisplayName || generateVariableDisplayName(component, metadata),
  }))
  return {
    ...values,
    FormulaTemplateApplicableLocations:
      values.FormulaTemplateApplicableLocations?.map((l) => (typeof l === 'object' ? l : { LocationId: l })) ?? [],
    FormulaTemplateApplicableProducts:
      values.FormulaTemplateApplicableProducts?.map((p) => (typeof p === 'object' ? p : { ProductId: p })) || [],
    FormulaTemplateCategoryId: values.FormulaTemplateCategoryId,
    FormulaTemplateVariables: formulaTemplateVariables ?? [],
    IsActive: true,
    IsVisible: true,
    Formula: values.Formula ? values.Formula : formula,
    FormulaTemplateId: viewMode === 'Edit' ? selectedTemplate?.FormulaTemplateId : undefined,
  }
}

export function joinFormulaDisplayNames<T extends { Percentage?: number | null }>(
  components: T[],
  getDisplayName: (component: T) => string
): string {
  if (components.length === 0) return ''

  return components.reduce((result, component, index) => {
    const isNegative = (component.Percentage ?? 0) < 0
    let displayName = getDisplayName(component)

    // If negative, convert "-X%" to "X%" for display
    if (isNegative && displayName.startsWith('-')) {
      displayName = displayName.slice(1)
    }

    if (index === 0) {
      return displayName
    }

    const operator = isNegative ? ' - ' : ' + '
    return result + operator + displayName
  }, '')
}

export function getFormulaAutoGeneratedDisplayText(
  formulaComponents: FormulaTemplateVariable[],
  metadata?: Partial<FormulaTemplateMetadata>
) {
  return joinFormulaDisplayNames(
    formulaComponents,
    (component) => component.DisplayName || generateVariableDisplayName(component, metadata)
  )
}

export function mapFormulaVariableToTemplateVariable(
  formulaVar: FormulaVariable,
  metadata?: FormulaTemplateMetadata
): FormulaTemplateVariable {
  return {
    AllowMultiOrigin: formulaVar.AllowMultiOrigin ?? null,
    CounterPartyMatchTypeCvId: formulaVar.CounterPartyMatchTypeCvId ?? null,
    Differential: formulaVar.Differential ?? 0,
    DisplayName:
      formulaVar.DisplayName ||
      generateVariableDisplayName(
        {
          Percentage: formulaVar.Percentage,
          PricePublisherId: getIdValue(formulaVar.PricePublisherId),
          PriceInstrumentId: getIdValue(formulaVar.PriceInstrumentId),
          PriceTypeCvId: getIdValue(formulaVar.PriceTypeCvId),
          PriceValuationRuleId: getIdValue(formulaVar.PriceValuationRuleId),
        },
        metadata
      ),
    FixedValue: typeof formulaVar.FixedValue === 'number' ? formulaVar.FixedValue : undefined,
    IsCost: formulaVar.IsCost ?? false,
    IsRequired: formulaVar.IsRequired ?? true,
    IsSystemVariable: formulaVar.IsSystemVariable ?? false,
    IsTemplateVariable: true,
    IsVisible: formulaVar.IsVisible ?? false,
    MissingOptionalPriceBehaviorCvId: formulaVar.MissingOptionalPriceBehaviorCvId ?? undefined,
    Percentage: formulaVar.Percentage ?? 100,
    PriceInstrumentId: getIdValue(formulaVar.PriceInstrumentId),
    PricePublisherId: getIdValue(formulaVar.PricePublisherId),
    PriceTypeCvId: getIdValue(formulaVar.PriceTypeCvId),
    PriceValuationRuleId: getIdValue(formulaVar.PriceValuationRuleId),
    SpecificCounterPartyId: formulaVar.SpecificCounterPartyId ?? null,
    SpecificLocationId: formulaVar.SpecificLocationId ?? null,
    SpecificProductId: formulaVar.SpecificProductId ?? null,
    SystemDataType: formulaVar.SystemDataType ?? '',
    TradeDateRuleCvId: formulaVar.TradeDateRuleCvId ?? null,
    UOMConversionOverride: formulaVar.UOMConversionOverride ?? undefined,
    ValueSourceCvId: formulaVar.ValueSourceCvId ?? null,
  }
}
