import { Vertical } from '@gravitate-js/excalibrr'
import { FormulaTemplateEndpoints } from '@modules/FormulaTemplates/Api/FormulaTemplateEndpoints'
import { FormulaTemplateDetails, FormulaTemplateVariable } from '@modules/FormulaTemplates/Api/types.schema'
import { usePriceFormulaTemplate } from '@modules/FormulaTemplates/Api/usePriceFormulaTemplate'
import { DrawerFooter } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/DrawerFooter'
import { DrawerHeader } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/DrawerHeader'
import { FormulaComponents } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/FormulaComponents'
import { PricingDisplaySection } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/PricingDisplaySection'
import { TemplateInfo } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/TemplateInfo'
import { ViewMode } from '@modules/FormulaTemplates/Util/formConstants'
import {
  generateVariableDisplayName,
  getAutoGeneratedPricingDisplayText,
  getPayload,
} from '@modules/FormulaTemplates/Util/formHelpers'
import { Drawer, Form } from 'antd'
import { Dispatch, SetStateAction, useEffect, useMemo, useState } from 'react'

interface FormulaTemplateDrawerProps {
  viewMode: ViewMode
  isDrawerVisible: boolean
  setIsDrawerVisible: Dispatch<SetStateAction<boolean>>
  selectedTemplate: Partial<FormulaTemplateDetails> | null
  setSelectedTemplate: Dispatch<SetStateAction<Partial<FormulaTemplateDetails> | null>>
  setViewMode?: Dispatch<SetStateAction<ViewMode>>
  existingTemplates?: FormulaTemplateDetails[]
  endpoints: FormulaTemplateEndpoints
  onSaveInvalidateKey?: string
}
export function FormulaTemplateDrawer({
  viewMode,
  isDrawerVisible,
  setIsDrawerVisible,
  selectedTemplate,
  setSelectedTemplate,
  setViewMode,
  existingTemplates = [],
  endpoints,
  onSaveInvalidateKey,
}: FormulaTemplateDrawerProps) {
  const [formulaComponents, setFormulaComponents] = useState<FormulaTemplateVariable[]>([])
  const { useSaveFormulaTemplateMutation, useMetadataQuery } = usePriceFormulaTemplate(endpoints, onSaveInvalidateKey)
  const [showCustomInput, setShowCustomInput] = useState(false)
  const [isSaving, setIsSaving] = useState(false)

  const [form] = Form.useForm()

  const { data: metadata } = useMetadataQuery(isDrawerVisible)

  const handleClose = () => {
    setIsSaving(false)
    setIsDrawerVisible(false)
    form.resetFields()
    setSelectedTemplate(null)
    setFormulaComponents([])
    setShowCustomInput(false)
    typeof setViewMode === 'function' && setViewMode('Create')
  }

  const autoGeneratedPricingText = useMemo(() => {
    if (!formulaComponents?.length) return 'No components added yet'
    return getAutoGeneratedPricingDisplayText(formulaComponents, metadata)
  }, [formulaComponents, metadata])

  const setFormFields = () => {
    if (!selectedTemplate) return

    // Set DisplayName to null when it matches auto-generated (so it stays dynamic), keep custom values
    const variablesWithResolvedNames =
      selectedTemplate.FormulaTemplateVariables?.map((variable) => ({
        ...variable,
        DisplayName:
          variable.DisplayName !== null && variable.DisplayName !== generateVariableDisplayName(variable, metadata)
            ? variable.DisplayName
            : null,
      })) ?? []
    setFormulaComponents(variablesWithResolvedNames)
    const categoryId = metadata?.FormulaTemplateCategories.some(
      (cat: { Text: string; Value: string }) => cat.Value == selectedTemplate.FormulaTemplateCategoryId?.toString()
    )
      ? selectedTemplate.FormulaTemplateCategoryId?.toString()
      : null
    const values = {
      FormulaTemplateApplicableProducts:
        selectedTemplate.FormulaTemplateApplicableProducts?.map((p) => p?.ProductId?.toString()) ?? [],
      FormulaTemplateApplicableLocations:
        selectedTemplate.FormulaTemplateApplicableLocations?.map((l) => l?.LocationId?.toString()) ?? [],
      FormulaTemplateCategoryId: categoryId,
      FormulaComponents: selectedTemplate.FormulaTemplateVariables ?? [],
      Name: viewMode === 'Duplicate' ? null : selectedTemplate.Name,
      FormulaTemplateVariables: selectedTemplate.FormulaTemplateVariables ?? [],
      PricingDisplayText: selectedTemplate.PricingDisplayText,
    }
    form.setFieldsValue(values)
    if (
      selectedTemplate.PricingDisplayText &&
      getAutoGeneratedPricingDisplayText(selectedTemplate.FormulaTemplateVariables ?? [], metadata) !=
        selectedTemplate.PricingDisplayText
    )
      setShowCustomInput(true)
  }

  useEffect(() => {
    if (selectedTemplate && metadata) {
      setFormFields()
    }
  }, [selectedTemplate, metadata])

  const onFinish = async (values: FormulaTemplateDetails) => {
    setIsSaving(true)
    const pricingDisplayText = autoGeneratedPricingText === 'No components added yet' ? null : autoGeneratedPricingText

    if (!showCustomInput) {
      values.PricingDisplayText = null
    }
    if (!showCustomInput && autoGeneratedPricingText?.length > 1000) {
      setIsSaving(false)
      return
    }
    const payload = getPayload({
      values,
      formulaComponents,
      autoGeneratedPricingDisplayText: pricingDisplayText,
      selectedTemplate,
      viewMode,
      metadata,
    })
    try {
      await useSaveFormulaTemplateMutation.mutateAsync(payload)
      handleClose()
    } catch (error) {
      setIsSaving(false)
      console.log('cannot save')
    }
  }

  return (
    <Drawer
      title={<DrawerHeader viewMode={viewMode} handleClose={handleClose} />}
      placement={'bottom'}
      height={'80%'}
      open={isDrawerVisible}
      closable={false}
      styles={{ header: { backgroundColor: 'var(--theme-color-1)', color: 'white' } }}
      onClose={handleClose}
      footer={<DrawerFooter form={form} handleClose={handleClose} isLoading={isSaving} />}
    >
      <Form form={form} layout={'vertical'} onFinish={onFinish}>
        <Vertical gap={10} style={{ width: '100%', maxWidth: '1800px', margin: '0 auto' }}>
          <TemplateInfo
            metadata={metadata}
            existingTemplates={existingTemplates}
            viewMode={viewMode}
            selectedTemplate={selectedTemplate}
          />
          <PricingDisplaySection
            pricingDisplayText={autoGeneratedPricingText}
            showCustomInput={showCustomInput}
            setShowCustomInput={setShowCustomInput}
            form={form}
            title='Pricing Display Name'
            checkboxLabel='Custom Pricing Display Name'
          />
          <FormulaComponents
            metadata={metadata}
            setFormulaComponents={setFormulaComponents}
            formulaComponents={formulaComponents}
            form={form}
          />
        </Vertical>
      </Form>
    </Drawer>
  )
}
