export const data = {
  FormulaId: null,
  FormulaResultId: 1474975,
  CalculationDate: '2022-12-02T16:20:03.037',
  CalculationName: '1676',
  ForCounterPartyId: 5071,
  ForCounterPartyName: 'Trafigura Pte Ltd',
  ForLocationId: 19447,
  ForLocationName: 'PhoenixAZ/KM',
  Formula: '(0.9000 * (0.033990 + Var_1)) + (0.1000 * (0.033990 + Var_2)) + (-0.1000 * Var_3)',
  ForProductId: 1105,
  ForProductName: '87CBG10%EH',
  Result: '2.1680',
  ResultComponents: [
    {
      FormulaResultComponentId: 12136286,
      ComponentDisplayName: 'OPIS - AZRBOB @ Los Angeles, California',
      ComponentName: 'Var_1',
      ComponentResult: '2.294500',
      ComponentResultSystemDataType: 'System.Decimal',
      ComponentStatus: 'A',
      Differential: null,
      EffectiveAsOfDate: '2022-12-01T00:00:00',
      IsRequired: true,
      Percentage: null,
      PriceInstrumentId: 126900,
      PriceInstrumentLocationId: 19460,
      PriceInstrumentName: 'OPIS - AZRBOB @ Los Angeles, California',
      PriceInstrumentOriginLocationId: null,
      PriceInstrumentProductId: 1129,
      PriceTypeCodeValueDisplay: 'Posting',
      PriceTypeCvId: 704,
      TradePeriodFromDateTime: null,
      TradePeriodToDateTime: null,
      UnitOfMeasureId: 3,
      UnitOfMeasureName: 'gal',
      UnitOfMeasureSymbol: 'gal',
      ValueSourceCodeValueDisplay: 'Database Price',
      ValueSourceCvId: 7200,
      IsMissing: false,
      TargetUomValue: null,
    },
    {
      FormulaResultComponentId: 12136287,
      ComponentDisplayName: 'OPIS - Ethanol @ Phoenix, Arizona',
      ComponentName: 'Var_2',
      ComponentResult: '2.380000',
      ComponentResultSystemDataType: 'System.Decimal',
      ComponentStatus: 'A',
      Differential: null,
      EffectiveAsOfDate: '2022-12-01T00:00:00',
      IsRequired: true,
      Percentage: null,
      PriceInstrumentId: 126905,
      PriceInstrumentLocationId: 19462,
      PriceInstrumentName: 'OPIS - Ethanol @ Phoenix, Arizona',
      PriceInstrumentOriginLocationId: null,
      PriceInstrumentProductId: 85,
      PriceTypeCodeValueDisplay: 'Posting',
      PriceTypeCvId: 704,
      TradePeriodFromDateTime: null,
      TradePeriodToDateTime: null,
      UnitOfMeasureId: 3,
      UnitOfMeasureName: 'gal',
      UnitOfMeasureSymbol: 'gal',
      ValueSourceCodeValueDisplay: 'Database Price',
      ValueSourceCvId: 7200,
      IsMissing: false,
      TargetUomValue: null,
    },
    {
      FormulaResultComponentId: 12136288,
      ComponentDisplayName: 'OPIS - US Ethanol RIN',
      ComponentName: 'Var_3',
      ComponentResult: '1.690000',
      ComponentResultSystemDataType: 'System.Decimal',
      ComponentStatus: 'A',
      Differential: null,
      EffectiveAsOfDate: '2022-12-01T00:00:00',
      IsRequired: true,
      Percentage: null,
      PriceInstrumentId: 11,
      PriceInstrumentLocationId: 93,
      PriceInstrumentName: 'OPIS - US Ethanol RIN',
      PriceInstrumentOriginLocationId: null,
      PriceInstrumentProductId: 186,
      PriceTypeCodeValueDisplay: 'Posting',
      PriceTypeCvId: 704,
      TradePeriodFromDateTime: null,
      TradePeriodToDateTime: null,
      UnitOfMeasureId: 3,
      UnitOfMeasureName: 'gal',
      UnitOfMeasureSymbol: 'gal',
      ValueSourceCodeValueDisplay: 'Database Price',
      ValueSourceCvId: 7200,
      IsMissing: false,
      TargetUomValue: null,
    },
  ],
  ResultStatus: 'A',
  ResultSystemDataType: 'System.Decimal',
  TargetUnitOfMeasureId: null,
  TargetUnitOfMeasureName: null,
  TargetUnitOfMeasureSymbol: null,
  FilledFormula: '2.1680 = (0.9000 * (0.033990 + 2.2945)) + (0.1000 * (0.033990 + 2.3800)) + (-0.1000 * 1.6900)',
  IsMissingPrices: false,
}
