import { Vertical } from '@gravitate-js/excalibrr'
import { FormulaTemplateEndpoints } from '@modules/FormulaTemplates/Api/FormulaTemplateEndpoints'
import { FormulaTemplateDetails, FormulaTemplateVariable } from '@modules/FormulaTemplates/Api/types.schema'
import { usePriceFormulaTemplate } from '@modules/FormulaTemplates/Api/usePriceFormulaTemplate'
import { DrawerFooter } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/DrawerFooter'
import { DrawerHeader } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/DrawerHeader'
import { Formula } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/Formula'
import { FormulaComponents } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/FormulaComponents'
import { TemplateInfo } from '@modules/FormulaTemplates/Components/CreateEditDrawer/Components/TemplateInfo'
import { ViewMode } from '@modules/FormulaTemplates/Util/formConstants'
import {
  generateVariableDisplayName,
  getFormulaAutoGeneratedDisplayText,
  getPayload,
} from '@modules/FormulaTemplates/Util/formHelpers'
import { Drawer, Form } from 'antd'
import { useForm } from 'antd/lib/form/Form'
import { Dispatch, SetStateAction, useEffect, useMemo, useState } from 'react'

interface FormulaTemplateDrawerProps {
  viewMode: ViewMode
  isDrawerVisible: boolean
  setIsDrawerVisible: Dispatch<SetStateAction<boolean>>
  selectedTemplate: Partial<FormulaTemplateDetails> | null
  setSelectedTemplate: Dispatch<SetStateAction<Partial<FormulaTemplateDetails> | null>>
  setViewMode?: Dispatch<SetStateAction<ViewMode>>
  existingTemplates?: FormulaTemplateDetails[]
  endpoints: FormulaTemplateEndpoints
}
export function FormulaTemplateDrawer({
  viewMode,
  isDrawerVisible,
  setIsDrawerVisible,
  selectedTemplate,
  setSelectedTemplate,
  setViewMode,
  existingTemplates = [],
  endpoints,
}: FormulaTemplateDrawerProps) {
  const [formulaComponents, setFormulaComponents] = useState<FormulaTemplateVariable[]>([])
  const { useSaveFormulaTemplateMutation, useMetadataQuery } = usePriceFormulaTemplate(endpoints)
  const [showCustomInput, setShowCustomInput] = useState(false)
  const [isSaving, setIsSaving] = useState(false)

  const [form] = useForm()

  const { data: metadata } = useMetadataQuery(isDrawerVisible)

  const handleClose = () => {
    setIsSaving(false)
    setIsDrawerVisible(false)
    form.resetFields()
    setSelectedTemplate(null)
    setFormulaComponents([])
    setShowCustomInput(false)
    typeof setViewMode === 'function' && setViewMode('Create')
  }

  const autoGenratedFormulaName = useMemo(() => {
    if (!formulaComponents?.length) return 'No components added yet'
    return getFormulaAutoGeneratedDisplayText(formulaComponents, metadata)
  }, [formulaComponents, metadata])

  const setFormFields = () => {
    if (!selectedTemplate) return

    // Map variables to add isDisplayNameCustomized flag
    const variablesWithFlag =
      selectedTemplate.FormulaTemplateVariables?.map((variable) => ({
        ...variable,
        isDisplayNameCustomized:
          variable.DisplayName !== null && variable.DisplayName !== generateVariableDisplayName(variable, metadata),
      })) ?? []
    setFormulaComponents(variablesWithFlag)
    const categoryId = metadata?.FormulaTemplateCategories.some(
      (cat: { Text: string; Value: string }) => cat.Value == selectedTemplate.FormulaTemplateCategoryId?.toString()
    )
      ? selectedTemplate.FormulaTemplateCategoryId?.toString()
      : null
    const values = {
      FormulaTemplateApplicableProducts:
        selectedTemplate.FormulaTemplateApplicableProducts?.map((p) => p?.ProductId?.toString()) ?? [],
      FormulaTemplateApplicableLocations:
        selectedTemplate.FormulaTemplateApplicableLocations?.map((l) => l?.LocationId?.toString()) ?? [],
      FormulaTemplateCategoryId: categoryId,
      FormulaComponents: selectedTemplate.FormulaTemplateVariables ?? [],
      Name: viewMode === 'Duplicate' ? null : selectedTemplate.Name,
      FormulaTemplateVariables: selectedTemplate.FormulaTemplateVariables ?? [],
      Formula: selectedTemplate.Formula,
    }
    form.setFieldsValue(values)
    if (
      selectedTemplate.Formula &&
      getFormulaAutoGeneratedDisplayText(selectedTemplate.FormulaTemplateVariables ?? [], metadata) !=
        selectedTemplate.Formula
    )
      setShowCustomInput(true)
  }

  useEffect(() => {
    if (selectedTemplate && metadata) {
      setFormFields()
    }
  }, [selectedTemplate, metadata])

  const onFinish = async (values: FormulaTemplateDetails) => {
    setIsSaving(true)
    const formulaValue = autoGenratedFormulaName === 'No components added yet' ? null : autoGenratedFormulaName
    const payload = getPayload({
      values,
      formulaComponents,
      formula: formulaValue,
      selectedTemplate,
      viewMode,
      metadata,
    })
    try {
      await useSaveFormulaTemplateMutation.mutateAsync(payload)
      handleClose()
    } catch (error) {
      setIsSaving(false)
      console.log('cannot save')
    }
  }

  return (
    <Drawer
      title={<DrawerHeader viewMode={viewMode} handleClose={handleClose} />}
      placement={'bottom'}
      height={'80%'}
      visible={isDrawerVisible}
      closable={false}
      headerStyle={{ backgroundColor: 'var(--theme-color-1)', color: 'white' }}
      onClose={handleClose}
      footer={<DrawerFooter form={form} handleClose={handleClose} isLoading={isSaving} />}
    >
      <Form form={form} layout={'vertical'} onFinish={onFinish}>
        <Vertical className={'gap-10'} style={{ width: '100%', maxWidth: '1800px', margin: '0 auto' }}>
          <TemplateInfo
            metadata={metadata}
            existingTemplates={existingTemplates}
            viewMode={viewMode}
            selectedTemplate={selectedTemplate}
          />
          <Formula
            formula={autoGenratedFormulaName}
            setShowCustomInput={setShowCustomInput}
            showCustomInput={showCustomInput}
          />
          <FormulaComponents
            metadata={metadata}
            setFormulaComponents={setFormulaComponents}
            formulaComponents={formulaComponents}
            form={form}
          />
        </Vertical>
      </Form>
    </Drawer>
  )
}
